In [5]:
import pandas as pd
import os
from datetime import datetime

# df_init = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\Automation.xlsx", sheet_name='BoP edit')
df_init = pd.read_excel(r"C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\Automation.xlsx", sheet_name='BoP edit')

path_dict = dict()
list_1 = ['IMF BOP Annual.xlsx', 'IMF BOP Quarterly.xlsx']
# directory_path= r'C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data'
directory_path= r'C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data'
for filename in os.listdir(directory_path):
    if filename in ['01 Emerging Market', '02 G7 Countries']:
        continue
    file_path = os.path.join(directory_path, filename)
    list_temp = []
    for filename2 in os.listdir(file_path):
        if any(word in str(filename2) for word in list_1):            
            list_temp.append(filename2)
            path_dict[filename] = list_temp
        else:
            continue

df_path = []
for k, v in path_dict.items():
    df_path.append(os.path.join(directory_path, k, v[1]))
    print(v[1]) ## to check the file name

df_all_annual = pd.DataFrame()
for x, y in enumerate(df_path):
    df = pd.read_excel(y)
    df = df[df[df.columns[0]].isin(df_init['desc'])]
    df_all_annual = pd.concat([df_all_annual, df]) 

df_all_annual.rename(columns={df_all_annual.columns[0]: 'Type'}, inplace=True)

df_all_annual_2 = df_all_annual[df_all_annual.columns[:4].to_list() + [dt for dt in df_all_annual.columns[4:].sort_values(ascending=True).to_list() if dt >= datetime(2019, 1, 1)]]

def sg_row(df:pd.DataFrame, main:bool = True) -> pd.DataFrame:
    var = df.columns[:4] if main else df.columns[4:]
    return df[var]

sg_add = {
 'FDI Assets':{'FDI Equity Assets': 0.74,'FDI Debt Assets': 0.26},
 'FDI Liabilities': {'FDI Equity Liabilities': 0.85,'FDI Debt Liabilities': 0.15},
 'Portfolio Assets': {'Portfolio Equity Assets': 0.57, 'Portfolio Debt Assets': 0.43}, 
 'Portfolio Liabilities': {'Portfolio Equity Liabilities': 0.67, 'Portfolio Debt Liabilities': 0.33},
 'Other Investment Assets': {'Currency and Deposits Assets': 0.5, 'Loans Assets': 0.29, 'Insurance and Pension Assets': 0.02, 'Trade Credits and Advances Assets': 0.09, 'OI Others Assets': 0.1},
 'Other Investment Liabilities': {'Currency and Deposits Liabilities': 0.5, 'Loans Liabilities': 0.29, 'Insurance and Pension Liabilities': 0.02, 'Trade Credits and Advances Liabilities': 0.09, 'OI Others Liabilities': 0.1},
 }

m = df_all_annual_2[(df_all_annual_2['Region']== 'Singapore')]['Type'].to_list()
df_init[(df_init['desc'].isin(m))]['group'].unique().tolist()

sg_item = [ 'BoP: Financial Account: Direct Investment: Assets',
            'BoP: Financial Account: Direct Investment: Liabilities',
            'BoP: Financial Account: Portfolio Investment: Assets',
            'BoP: Financial Account: Portfolio Investment: Liabilities',
            'BoP: Financial Account: Other Investment: Assets',
            'BoP: Financial Account: Other Investment: Liabilities']

sg_df = pd.DataFrame(columns=df_all_annual_2.columns)

# ensure the zip between sg_item and sg_add is correct
for x, y in zip(sg_item, sg_add.values()):
    multiplier = list(y.values())
    row_type = list(y.keys())
    df_temp = df_all_annual_2[(df_all_annual_2['Type'] == x) &(df_all_annual_2['Region']== 'Singapore')]
    # print(multiplier, row_type)
    for n in range(len(row_type)):
        col1 = sg_row(df_temp, main=True)
        col1.iat[0, 0] = list(df_init[(df_init['short_title']==row_type[n])]['desc'])[0]
        col2 = sg_row(df_temp, main=False) * multiplier[n]
        merged = pd.concat([col1, col2], axis=1)
        sg_df = pd.concat([sg_df, merged], axis=0)

# concat to the main df
df_all_annual_2 = pd.concat([df_all_annual_2, sg_df], axis=0)

init_dict = df_init.to_dict()
df_dict = dict()
for x in init_dict['desc'].values():
    df_temp = df_all_annual_2[(df_all_annual_2[df_all_annual_2.columns[0]] == x)].reset_index(drop=True)
    df_dict[x] = df_temp

df_all_annual_2[df_all_annual_2.columns[:8]]

BN IMF BOP Quarterly.xlsx
KH IMF BOP Quarterly.xlsx
CH IMF BOP Quarterly.xlsx
HK IMF BOP Quarterly.xlsx
IN IMF BOP Quarterly.xlsx
ID IMF BOP Quarterly.xlsx
KR IMF BOP Quarterly.xlsx
LA IMF BOP Quarterly.xlsx
MY IMF BOP Quarterly.xlsx
MG IMF BOP Quarterly.xlsx
NP IMF BOP Quarterly.xlsx
PG IMF BOP Quarterly.xlsx
PH IMF BOP Quarterly.xlsx
SG IMF BOP Quarterly.xlsx
LK IMF BOP Quarterly.xlsx
TH IMF BOP Quarterly.xlsx
VN IMF BOP Quarterly.xlsx

C:\Users\Admin\AppData\Local\Temp\ipykernel_15276\510568210.py:75: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  sg_df = pd.concat([sg_df, merged], axis=0)

,Type,Region,Unit,Last Update Time,2019-03-01 00:00:00,2019-06-01 00:00:00,2019-09-01 00:00:00,2019-12-01 00:00:00
0,BoP: Current Account,Brunei,USD mn,2024-10-24,NaN,NaN,NaN,NaN
3,BoP: Current Account: Goods,Brunei,USD mn,2024-10-24,NaN,NaN,NaN,NaN
10,BoP: Current Account: Services,Brunei,USD mn,2024-10-24,NaN,NaN,NaN,NaN
73,BoP: Current Account: Primary Income,Brunei,USD mn,2024-10-24,NaN,NaN,NaN,NaN
82,BoP: Current Account: Secondary Income,Brunei,USD mn,2024-10-24,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
27,BoP: Financial Account: Other Investment: Liab...,Singapore,USD mn,2024-09-26,1143.943308,18030.074820,11819.998546,-4062.894235
27,BoP: Financial Account: Other Investment: Liab...,Singapore,USD mn,2024-09-26,663.487119,10457.443396,6855.599157,-2356.478656
27,BoP: Financial Account: Other Investment: Liab...,Singapore,USD mn,2024-09-26,45.757732,721.202993,472.799942,-162.515769
27,BoP: Financial Account: Other Investment: Liab...,Singapore,USD mn,2024-09-26,205.909796,3245.413468,2127.599738,-731.320962
27,BoP: Financial Account: Other Investment: Liab...,Singapore,USD mn,2024-09-26,228.788662,3606.014964,2363.999709,-812.578847

In [24]:
len(df_all_annual_2.columns)

31

In [29]:
df_init_tw = pd.read_excel(r"C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\Automation.xlsx", sheet_name='Taiwan BoP')
df_tw = pd.read_excel(r"C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data\Chinese Taipei (Taiwan) (TW)\TW CB BOP Quarterly.xlsx")
df_tw.rename(columns={df_tw.columns[0]: 'Type'}, inplace=True)
df_tw = df_tw[df_tw['Type'].isin(df_init_tw['desc'])]

for x, y in enumerate(df_tw['Type'].to_list()):
    df_tw.iat[x,0] = list(df_init_tw[(df_init_tw['desc'] == y)]['desc2'])[0]
    # print([y,list(df_init_tw[(df_init_tw['desc'] == y)]['desc2'])[0]])

len(df_tw.columns)

df_tw

,Type,Region,Unit,Last Update Time,2015-03-01 00:00:00,2015-06-01 00:00:00,2015-09-01 00:00:00,2015-12-01 00:00:00,2016-03-01 00:00:00,2016-06-01 00:00:00,...,2022-06-01 00:00:00,2022-09-01 00:00:00,2022-12-01 00:00:00,2023-03-01 00:00:00,2023-06-01 00:00:00,2023-09-01 00:00:00,2023-12-01 00:00:00,2024-03-01 00:00:00,2024-06-01 00:00:00,2024-09-01 00:00:00
0,BoP: Current Account,Taiwan,USD mn,2024-11-20,21841,16147,15561,19220,20315,17761,...,24287,22311,23412,19350,23551,29124,33824,29652,22697,27477.0
4,BoP: Current Account: Goods,Taiwan,USD mn,2024-11-20,18944,17379,18456,18360,17175,17208,...,14961,18020,15672,12157,22316,31123,30021,24641,21855,29170.0
8,BoP: Current Account: Services,Taiwan,USD mn,2024-11-20,-2674,-2782,-3019,-2305,-2242,-2550,...,3749,3330,683,-1616,-2289,-4308,-1842,-2239,-4226,-4600.0
9,BoP: Current Account: Primary Income,Taiwan,USD mn,2024-11-20,6289,2728,926,3836,5937,3987,...,6228,1793,8110,9950,4765,3540,7038,8465,6166,4280.0
12,BoP: Current Account: Secondary Income,Taiwan,USD mn,2024-11-20,-718,-1178,-802,-671,-555,-884,...,-651,-832,-1053,-1141,-1241,-1231,-1393,-1215,-1098,-1373.0
28,BoP: Financial Account: Direct Investment: Assets,Taiwan,USD mn,2024-11-20,2905,4517,4128,3159,2839,3354,...,3415,2217,4906,5600,2986,6176,9990,3571,10705,10658.0
29,BoP: Financial Account: Direct Investment: Ass...,Taiwan,USD mn,2024-11-20,2881,3952,3688,3128,2635,3221,...,2550,2630,5008,5447,3220,5637,10679,2779,10376,11090.0
32,BoP: Financial Account: Direct Investment: Ass...,Taiwan,USD mn,2024-11-20,24,565,440,31,204,133,...,865,-413,-102,153,-234,539,-689,792,329,-432.0
33,BoP: Financial Account: Direct Investment: Lia...,Taiwan,USD mn,2024-11-20,1067,288,784,252,753,658,...,3643,2240,2184,2181,2011,610,1617,1287,4151,2647.0
34,BoP: Financial Account: Direct Investment: Lia...,Taiwan,USD mn,2024-11-20,1034,367,809,268,757,517,...,3307,370,1247,516,2703,546,1020,736,823,332.0
37,BoP: Financial Account: Direct Investment: Lia...,Taiwan,USD mn,2024-11-20,33,-79,-25,-16,-4,141,...,336,1870,937,1665,-692,64,597,551,3328,2315.0
39,BoP: Financial Account: Portfolio Investment: ...,Taiwan,USD mn,2024-11-20,14195,13439,14227,14479,21126,17181,...,13594,7563,3106,26398,19271,15551,11599,26222,16095,6500.0
40,BoP: Financial Account: Portfolio Investment: ...,Taiwan,USD mn,2024-11-20,5713,-1039,-552,2800,1894,-846,...,-593,2004,418,5390,2735,5715,4118,6443,6413,4141.0
46,BoP: Financial Account: Portfolio Investment: ...,Taiwan,USD mn,2024-11-20,8482,14478,14779,11679,19232,18027,...,14187,5559,2688,21008,16536,9836,7481,19779,9682,2359.0
58,BoP: Financial Account: Portfolio Investment: ...,Taiwan,USD mn,2024-11-20,3982,3020,-5505,-269,3314,1131,...,-13052,-20208,2365,8448,6195,-19571,12270,4986,2994,-17812.0
59,BoP: Financial Account: Portfolio Investment: ...,Taiwan,USD mn,2024-11-20,4620,2479,-3573,218,4728,1570,...,-13084,-19504,2584,8781,6276,-19702,11827,5323,2711,-18881.0
65,BoP: Financial Account: Portfolio Investment: ...,Taiwan,USD mn,2024-11-20,-638,541,-1932,-487,-1414,-439,...,32,-704,-219,-333,-81,131,443,-337,283,1069.0
80,BoP: Financial Account: Financial Derivatives ...,Taiwan,USD mn,2024-11-20,-1898,-2583,-2973,-3773,-3804,-2364,...,-5831,-4359,-5860,-4937,-5002,-4461,-5815,-5933,-6169,-7814.0
86,BoP: Financial Account: Financial Derivatives ...,Taiwan,USD mn,2024-11-20,-3232,-2757,-4159,-3274,-3898,-2356,...,-7058,-6918,-6184,-5484,-4954,-5334,-5493,-6440,-6442,-7532.0
93,BoP: Financial Account: Other Investment: Assets,Taiwan,USD mn,2024-11-20,2345,10900,-19201,-10570,-2781,804,...,6545,-6514,-13010,-17397,11671,-16661,14835,-1358,-7442,2650.0
94,BoP: Financial Account: Other Investment: Asse...,Taiwan,USD mn,2024-11-20,4,0,4,0,2,0,...,0,5,0,9,0,0,0,0,6,2.0
96,BoP: Financial Account: Other Investment: Asse...,Taiwan,USD mn,2024-11-20,-3281,9092,-15854,-6573,1278,3764,...,2224,-10951,-749,-10499,7498,-17761,6743,-1502,-9572,2582.0
108,BoP: Financial Account: Other Investment: Asse...,Taiwan,USD mn,2024-11-20,3065,2004,-4428,2565,3573,659,...,1821,-44,-2266,-3509,-4021,-8528,9828,-6433,-522,2196.0
123,BoP: Financial Account: Other Investment: Asse...,Taiwan,USD mn,2024-11-20,-698,18,-176,-43,-2667,-1204,...,-1485,39,-607,-2401,2409,4448,3283,793,150,2728.0
129,BoP: Financial Account: Other Investment: Asse...,Taiwan,USD mn,2024-11-20,3255,-214,1253,-6519,-4967,-2415,...,3985,4437,-9388,-997,5785,5180,-5019,5784,2496,-4858.0
141,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,-5015,10933,-3350,-14481,3161,5215,...,13666,-3321,-22853,-6203,5482,-1307,-4735,-6388,-1955,10187.0
142,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
144,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,-8255,1966,-311,-5578,-1748,2232,...,5830,-550,-10510,-10689,928,-3789,5243,-11910,3636,13945.0
151,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,2184,5980,-2573,-5850,1388,2756,...,3165,-4820,-8430,2487,5649,5902,-2661,4221,-4417,464.0
169,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,-213,350,309,-709,2535,1323,...,2188,-568,622,1825,-3008,-4432,-3095,-1461,-147,-2888.0
175,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,1269,2637,-775,-2344,986,-1096,...,2483,2617,-4535,174,1913,1012,-4222,2762,-1027,-1334.0
188,BoP: Financial Account: Official Reserve Assets,Taiwan,USD mn,2024-11-20,3811,4174,5685,1341,3845,3153,...,3815,-4119,10931,4716,5223,1013,3390,-326,5458,1610.0
194,BoP: Financial Account: Other Investment: Liab...,Taiwan,USD mn,2024-11-20,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [18]:
# df_tw['Type'].to_list()
df_tw.iat[1,0]

'BoP: CU: GS: Goods'

In [10]:
#checking

temp_list = []

for x in df_init.desc.to_list():
    # print(len(df_dict[x]), x) if len(df_dict[x]) == 0 else print(x)
    temp_list.append([x, len(df_dict[x])])

# print(temp_list)
temp_list
# df_dict['BoP: Financial Account: Other Investment: Liabilities: Other Accounts Receivable/Payable'].head(2)
# df_init.desc.to_list()

# [16, 14, 14, 17, 13, 13, 11, 17, 7, 16, 15, 8, 13, 16, 17, 17, 17, 17, 17, 17, 17, 16, 16, 17, 14, 13, 11, 17, 6, 16, 16, 8, 14, 15, 14]
# [16, 14, 14, 17, 13, 13, 11, 17, 7, 16, 15, 8, 13, 16, 17, 17, 17, 17, 17, 17, 17, 16, 16, 17, 14, 13, 11, 17, 6, 16, 16, 8, 14, 15, 14]
# [16, 15, 15, 17, 14, 14, 11, 17, 7, 17, 16, 9, 14, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 15, 14, 11, 17, 6, 17, 17, 9, 15, 16, 14]

[['BoP: Financial Account: Direct Investment: Assets', 16],
 ['BoP: Financial Account: Direct Investment: Assets: Equity', 15],
 ['BoP: Financial Account: Direct Investment: Assets: Debt Instruments', 15],
 ['BoP: Financial Account: Portfolio Investment: Assets', 17],
 ['BoP: Financial Account: Portfolio Investment: Assets: Equity', 14],
 ['BoP: Financial Account: Portfolio Investment: Assets: Debt Securities', 14],
 ['BoP: Financial Account: Financial Derivatives & Employee Stock Options: Assets',
  11],
 ['BoP: Financial Account: Other Investment: Assets', 17],
 ['BoP: Financial Account: Other Investment: Assets: Other Equity', 7],
 ['BoP: Financial Account: Other Investment: Assets: Currency & Deposits', 17],
 ['BoP: Financial Account: Other Investment: Assets: Loans', 16],
 ['BoP: Financial Account: Other Investment: Assets: Insurance, Pension & Standardized Guarantee Schemes',
  9],
 ['BoP: Financial Account: Other Investment: Assets: Trade Credit & Advances',
  14],
 ['BoP: Financial Account: Other Investment: Assets: Other Accounts Receivable',
  17],
 ['BoP: Financial Account: Official Reserve Assets', 17],
 ['BoP: Current Account', 17],
 ['BoP: Current Account: Goods', 17],
 ['BoP: Current Account: Services', 17],
 ['BoP: Current Account: Primary Income', 17],
 ['BoP: Current Account: Secondary Income', 17],
 ['BoP: Financial Account: Direct Investment: Liabilities', 17],
 ['BoP: Financial Account: Direct Investment: Liabilities: Equity', 17],
 ['BoP: Financial Account: Direct Investment: Liabilities: Debt Instruments',
  17],
 ['BoP: Financial Account: Portfolio Investment: Liabilities', 17],
 ['BoP: Financial Account: Portfolio Investment: Liabilities: Equity', 15],
 ['BoP: Financial Account: Portfolio Investment: Liabilities: Debt Securities',
  14],
 ['BoP: Financial Account: Financial Derivatives & Employee Stock Options: Liabilities',
  11],
 ['BoP: Financial Account: Other Investment: Liabilities', 17],
 ['BoP: Financial Account: Other Investment: Liabilities: Other Equity', 6],
 ['BoP: Financial Account: Other Investment: Liabilities: Currency & Deposits',
  17],
 ['BoP: Financial Account: Other Investment: Liabilities: Loans', 17],
 ['BoP: Financial Account: Other Investment: Liabilities: Insurance, Pension & Standardized Guarantee Schemes',
  9],
 ['BoP: Financial Account: Other Investment: Liabilities: Trade Credit & Advances',
  15],
 ['BoP: Financial Account: Other Investment: Liabilities: Other Accounts Payable',
  16],
 ['BoP: Financial Account: Other Investment: Liabilities: SDRs', 14]]

In [79]:
# df_all_annual_2[df_all_annual_2.columns[4:]]
# (df_all_annual_2[x] + df_all_annual_2[x+1]).div(1000)
num1, num2 = 0, 1
df_col = df_all_annual_2.columns[4:][:-1]
df_temp_col_1 = df_all_annual_2[df_all_annual_2.columns[:4]].reset_index(drop=True)

for x in range(len(df_col)//2):
    df_col_temp = (df_all_annual_2[df_col[num1]] + df_all_annual_2[df_col[num1 + 1]]).div(1000)
    year = df_col[num1].year
    df_col_temp.reset_index(drop=True, inplace=True)
    df_temp_col_1[f'{num2}H{year}'] = df_col_temp
    num1 += 2
    num2 += 1
    if num2 == 3:
        num2 = 1

df_temp_col_1.drop(columns=['Last Update Time', 'Unit'], inplace=True)
df_temp_col_1

# len((df_all_annual_2[df_col[num]] + df_all_annual_2[df_col[num + 1]]).div(1000))
# df_temp_col_1

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,BoP: Current Account,Brunei,NaN,NaN,1.519496,-1.005783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BoP: Current Account: Goods,Brunei,NaN,NaN,1.963671,-0.604498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BoP: Current Account: Services,Brunei,NaN,NaN,-0.414720,-0.440466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BoP: Current Account: Primary Income,Brunei,NaN,NaN,0.151028,0.208608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BoP: Current Account: Secondary Income,Brunei,NaN,NaN,-0.180482,-0.169427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,BoP: Financial Account: Other Investment: Liab...,Singapore,19.174018,7.757104,53.206475,-5.451792,9.408786,25.093333,25.067774,-15.567074,-22.994907,12.471790,12.870555,NaN,NaN
516,BoP: Financial Account: Other Investment: Liab...,Singapore,11.120931,4.499121,30.859755,-3.162040,5.457096,14.554133,14.539309,-9.028903,-13.337046,7.233638,7.464922,NaN,NaN
517,BoP: Financial Account: Other Investment: Liab...,Singapore,0.766961,0.310284,2.128259,-0.218072,0.376351,1.003733,1.002711,-0.622683,-0.919796,0.498872,0.514822,NaN,NaN
518,BoP: Financial Account: Other Investment: Liab...,Singapore,3.451323,1.396279,9.577165,-0.981323,1.693581,4.516800,4.512199,-2.802073,-4.139083,2.244922,2.316700,NaN,NaN
519,BoP: Financial Account: Other Investment: Liab...,Singapore,3.834804,1.551421,10.641295,-1.090358,1.881757,5.018667,5.013555,-3.113415,-4.598981,2.494358,2.574111,NaN,NaN

In [80]:
test2 = df_all_annual_2[(df_all_annual_2['Region'] == 'Singapore')]['Type'].unique().tolist()
test = df_all_annual_2[(df_all_annual_2['Type'].isin(test2)) & (df_all_annual_2['Region'] == 'Singapore')]
for x in range(len(test)):
    test.iat[x, 0] = df_init[(df_init['desc'] == test2[x])]['short_title'].values[0]
# test.iat[0, 0] = df_init[(df_init['desc']==test2)]['short_title'].values[0]
test[test.columns[:8]]

# len(df_init)

,Type,Region,Unit,Last Update Time,2019-03-01 00:00:00,2019-06-01 00:00:00,2019-09-01 00:00:00,2019-12-01 00:00:00
0,Current Account,Singapore,USD mn,2024-09-26,14526.980143,14734.021224,16087.425469,15098.063664
3,Trade Balance (Goods),Singapore,USD mn,2024-09-26,22145.198199,25310.822045,24963.958505,23887.487164
6,Trade Balance (Services),Singapore,USD mn,2024-09-26,3525.872887,2922.245587,4561.442629,3952.545108
9,Investment Income,Singapore,USD mn,2024-09-26,-9606.333506,-11637.121620,-11584.662369,-10841.865923
12,Current Transfers,Singapore,USD mn,2024-09-26,-1537.757437,-1861.924788,-1853.313297,-1900.102684
17,FDI Assets,Singapore,USD mn,2024-09-26,13831.106518,18699.863074,20115.298851,15082.440956
18,FDI Liabilities,Singapore,USD mn,2024-09-26,22930.538127,21176.927967,28230.597702,33514.009095
20,Portfolio Assets,Singapore,USD mn,2024-09-26,8900.716026,68550.858233,22924.863057,13113.833064
21,Portfolio Liabilities,Singapore,USD mn,2024-09-26,1383.701188,4703.041714,-1597.653788,1694.880446
23,Financial Derivative Assets,Singapore,USD mn,2024-09-26,942.275042,2615.995892,3692.738378,3729.206396
24,Financial Derivative Liabilities,Singapore,USD mn,2024-09-26,1284.195763,-461.024989,1433.103883,2051.488925
26,Other Investment Assets,Singapore,USD mn,2024-09-26,9936.664944,9308.010172,17398.080372,10140.824410
27,Other Investment Liabilities,Singapore,USD mn,2024-09-26,2287.886617,36060.149641,23639.997091,-8125.788470
28,SDR Liabilities,Singapore,USD mn,2024-09-26,0.000000,0.000000,0.000000,0.000000
29,Official Reserve Assets,Singapore,USD mn,2024-09-26,9527.423046,-23488.801408,3011.125115,2589.702215
17,FDI Equity Assets,Singapore,USD mn,2024-09-26,10235.018823,13837.898675,14885.321150,11161.006308
17,FDI Debt Assets,Singapore,USD mn,2024-09-26,3596.087695,4861.964399,5229.977701,3921.434649
18,FDI Equity Liabilities,Singapore,USD mn,2024-09-26,19490.957408,18000.388772,23996.008047,28486.907731
18,FDI Debt Liabilities,Singapore,USD mn,2024-09-26,3439.580719,3176.539195,4234.589655,5027.101364
20,Portfolio Equity Assets,Singapore,USD mn,2024-09-26,5073.408135,39073.989193,13067.171942,7474.884847
20,Portfolio Debt Assets,Singapore,USD mn,2024-09-26,3827.307891,29476.869040,9857.691114,5638.948218
21,Portfolio Equity Liabilities,Singapore,USD mn,2024-09-26,927.079796,3151.037948,-1070.428038,1135.569899
21,Portfolio Debt Liabilities,Singapore,USD mn,2024-09-26,456.621392,1552.003765,-527.225750,559.310547
26,Currency and Deposits Assets,Singapore,USD mn,2024-09-26,4968.332472,4654.005086,8699.040186,5070.412205
26,Loans Assets,Singapore,USD mn,2024-09-26,2881.632834,2699.322950,5045.443308,2940.839079
26,Insurance and Pension Assets,Singapore,USD mn,2024-09-26,198.733299,186.160203,347.961607,202.816488
26,Trade Credits and Advances Assets,Singapore,USD mn,2024-09-26,894.299845,837.720915,1565.827234,912.674197
26,OI Others Assets,Singapore,USD mn,2024-09-26,993.666494,930.801017,1739.808037,1014.082441
27,Currency and Deposits Liabilities,Singapore,USD mn,2024-09-26,1143.943308,18030.074820,11819.998546,-4062.894235
27,Loans Liabilities,Singapore,USD mn,2024-09-26,663.487119,10457.443396,6855.599157,-2356.478656
27,Insurance and Pension Liabilities,Singapore,USD mn,2024-09-26,45.757732,721.202993,472.799942,-162.515769
27,Trade Credits and Advances Liabilities,Singapore,USD mn,2024-09-26,205.909796,3245.413468,2127.599738,-731.320962
27,OI Others Liabilities,Singapore,USD mn,2024-09-26,228.788662,3606.014964,2363.999709,-812.578847

In [333]:
sg_item2 = df_init[(df_init['short_title'].isin(sg_item))]['desc'].to_list()
sg_df = pd.DataFrame(columns=df_all_annual_2.columns)

for x, y in zip(sg_item2, sg_add.values()):
    multiplier = list(y.values())
    row_type = list(y.keys())
    df_temp = df_all_annual_2[(df_all_annual_2['Type'] == x) &(df_all_annual_2['Region']== 'Singapore')]
    for n in range(len(row_type)):
        col1 = sg_row(df_temp, main=True)
        col1.iat[0, 0] = list(df_init[(df_init['short_title']==row_type[n])]['desc'])[0]
        col2 = sg_row(df_temp, main=False) * multiplier[n]
        merged = pd.concat([col1, col2], axis=1)
        sg_df = pd.concat([sg_df, merged], axis=0)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18184\1036337144.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  sg_df = pd.concat([sg_df, merged], axis=0)

In [292]:
df_temp_col_1[(df_temp_col_1['Region'] == 'Singapore')].sort_values(by='Type', ascending=True)['Type'].unique().tolist()

['BoP: Current Account',
 'BoP: Current Account: Goods',
 'BoP: Current Account: Primary Income',
 'BoP: Current Account: Secondary Income',
 'BoP: Current Account: Services',
 'BoP: Financial Account: Direct Investment: Assets',
 'BoP: Financial Account: Direct Investment: Assets: Debt Instruments',
 'BoP: Financial Account: Direct Investment: Assets: Equity',
 'BoP: Financial Account: Direct Investment: Liabilities',
 'BoP: Financial Account: Direct Investment: Liabilities: Debt Instruments',
 'BoP: Financial Account: Direct Investment: Liabilities: Equity',
 'BoP: Financial Account: Financial Derivatives & Employee Stock Options: Assets',
 'BoP: Financial Account: Financial Derivatives & Employee Stock Options: Liabilities',
 'BoP: Financial Account: Official Reserve Assets',
 'BoP: Financial Account: Other Investment: Assets',
 'BoP: Financial Account: Other Investment: Assets: Currency & Deposits',
 'BoP: Financial Account: Other Investment: Assets: Insurance, Pension & Standardized Guarantee Schemes',
 'BoP: Financial Account: Other Investment: Assets: Loans',
 'BoP: Financial Account: Other Investment: Assets: Other Accounts Receivable',
 'BoP: Financial Account: Other Investment: Assets: Trade Credit & Advances',
 'BoP: Financial Account: Other Investment: Liabilities',
 'BoP: Financial Account: Other Investment: Liabilities: Currency & Deposits',
 'BoP: Financial Account: Other Investment: Liabilities: Insurance, Pension & Standardized Guarantee Schemes',
 'BoP: Financial Account: Other Investment: Liabilities: Loans',
 'BoP: Financial Account: Other Investment: Liabilities: Other Accounts Payable',
 'BoP: Financial Account: Other Investment: Liabilities: SDRs',
 'BoP: Financial Account: Other Investment: Liabilities: Trade Credit & Advances',
 'BoP: Financial Account: Portfolio Investment: Assets',
 'BoP: Financial Account: Portfolio Investment: Assets: Debt Securities',
 'BoP: Financial Account: Portfolio Investment: Assets: Equity',
 'BoP: Financial Account: Portfolio Investment: Liabilities',
 'BoP: Financial Account: Portfolio Investment: Liabilities: Debt Securities',
 'BoP: Financial Account: Portfolio Investment: Liabilities: Equity']

In [65]:
df_temp_col_1['Type'].unique()

array(['BoP: Current Account', 'BoP: Current Account: Goods',
       'BoP: Current Account: Services',
       'BoP: Current Account: Primary Income',
       'BoP: Current Account: Secondary Income',
       'BoP: Financial Account: Direct Investment: Liabilities',
       'BoP: Financial Account: Direct Investment: Liabilities: Equity',
       'BoP: Financial Account: Direct Investment: Liabilities: Debt Instruments',
       'BoP: Financial Account: Portfolio Investment: Assets',
       'BoP: Financial Account: Portfolio Investment: Assets: Equity',
       'BoP: Financial Account: Portfolio Investment: Assets: Debt Securities',
       'BoP: Financial Account: Portfolio Investment: Liabilities',
       'BoP: Financial Account: Portfolio Investment: Liabilities: Equity',
       'BoP: Financial Account: Portfolio Investment: Liabilities: Debt Securities',
       'BoP: Financial Account: Other Investment: Assets',
       'BoP: Financial Account: Other Investment: Assets: Currency & Deposits',
       'BoP: Financial Account: Other Investment: Assets: Loans',
       'BoP: Financial Account: Other Investment: Assets: Other Accounts Receivable',
       'BoP: Financial Account: Other Investment: Liabilities',
       'BoP: Financial Account: Other Investment: Liabilities: Currency & Deposits',
       'BoP: Financial Account: Other Investment: Liabilities: Loans',
       'BoP: Financial Account: Other Investment: Liabilities: Other Accounts Payable',
       'BoP: Financial Account: Official Reserve Assets',
       'BoP: Financial Account: Direct Investment: Assets',
       'BoP: Financial Account: Direct Investment: Assets: Equity',
       'BoP: Financial Account: Direct Investment: Assets: Debt Instruments',
       'BoP: Financial Account: Other Investment: Assets: Trade Credit & Advances',
       'BoP: Financial Account: Other Investment: Liabilities: Trade Credit & Advances',
       'BoP: Financial Account: Other Investment: Liabilities: SDRs',
       'BoP: Financial Account: Financial Derivatives & Employee Stock Options: Assets',
       'BoP: Financial Account: Financial Derivatives & Employee Stock Options: Liabilities',
       'BoP: Financial Account: Other Investment: Assets: Other Equity',
       'BoP: Financial Account: Other Investment: Assets: Insurance, Pension & Standardized Guarantee Schemes',
       'BoP: Financial Account: Other Investment: Liabilities: Insurance, Pension & Standardized Guarantee Schemes',
       'BoP: Financial Account: Other Investment: Liabilities: Other Equity'],
      dtype=object)

In [59]:
AP_RF = df_temp_col_1.groupby(['Type']).sum().reset_index()
AP_RF

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,BoP: Current Account,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,86.257296,154.800319,130.703136,368.119217,216.680499,298.658110,208.581937,290.167992,199.157660,224.737276,210.730190,0.0,0.0
1,BoP: Current Account: Goods,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,151.435730,257.171185,213.682627,470.361196,273.981596,370.600977,307.318617,314.787502,271.153122,318.225215,304.096047,0.0,0.0
2,BoP: Current Account: Primary Income,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,-61.135974,-99.587809,-95.223764,-131.360304,-109.548719,-151.369465,-199.513393,-134.891884,-139.429608,-157.479440,-151.542042,0.0,0.0
3,BoP: Current Account: Secondary Income,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,64.017586,68.507694,61.293253,76.159517,71.488601,78.285974,78.453667,92.719123,85.852313,95.061762,90.277756,0.0,0.0
4,BoP: Current Account: Services,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,-68.060046,-71.290751,-49.049109,-47.041064,-19.240979,1.140623,22.323046,17.553123,-18.418167,-31.070262,-32.101699,0.0,0.0
5,BoP: Financial Account: Direct Investment: Assets,CambodiaChinaHong Kong SAR (China)IndiaIndones...,143.454150,174.716555,174.427470,180.526686,220.698431,236.519163,265.349687,231.775066,215.966799,215.093167,226.974903,0.0,0.0
6,BoP: Financial Account: Direct Investment: Ass...,CambodiaChinaHong Kong SAR (China)IndiaIndones...,11.367627,16.173554,17.835635,14.092506,34.369468,22.179620,61.657512,32.497732,51.251933,49.209122,52.875401,0.0,0.0
7,BoP: Financial Account: Direct Investment: Ass...,CambodiaChinaHong Kong SAR (China)IndiaIndones...,99.262680,123.153261,137.758488,145.047189,158.189008,180.839568,176.500379,171.538985,138.046601,131.157362,147.276183,0.0,0.0
8,BoP: Financial Account: Direct Investment: Lia...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,219.304128,262.419214,232.598709,339.261923,404.199226,371.041467,378.429163,245.874268,245.545203,199.760108,195.325550,0.0,0.0
9,BoP: Financial Account: Direct Investment: Lia...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,29.136678,15.882661,27.958670,39.182259,47.224722,52.003328,50.176643,12.338948,8.202694,-14.566358,-13.238112,0.0,0.0
10,BoP: Financial Account: Direct Investment: Lia...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,146.059984,184.791947,161.465314,262.462581,281.619563,257.006936,256.845789,156.165363,151.287053,125.164540,127.336255,0.0,0.0
11,BoP: Financial Account: Financial Derivatives ...,ChinaHong Kong SAR (China)IndiaIndonesiaLaosMa...,-22.489857,-12.181328,-20.570723,-18.966652,-45.287658,-24.934654,-14.568555,-57.043978,-7.232229,-43.018229,-20.592167,0.0,0.0
12,BoP: Financial Account: Financial Derivatives ...,ChinaHong Kong SAR (China)IndiaIndonesiaLaosMa...,-21.626485,-18.198347,-25.937015,-19.463543,-42.421549,-18.339162,-32.152818,-42.884673,-11.743319,-40.771249,-40.718197,0.0,0.0
13,BoP: Financial Account: Official Reserve Assets,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,43.297870,35.139625,93.947124,215.128490,165.019838,198.823668,-135.663355,-12.320895,100.525514,10.598702,32.480147,0.0,0.0
14,BoP: Financial Account: Other Investment: Assets,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,5.147885,176.142457,224.036542,335.164711,420.696063,288.951363,217.540765,-4.063728,-78.632216,200.149941,90.494683,0.0,0.0
15,BoP: Financial Account: Other Investment: Asse...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,-8.369939,134.695828,55.148791,202.599555,146.712466,127.623620,47.551046,37.092600,-30.616730,138.423727,2.586694,0.0,0.0
16,BoP: Financial Account: Other Investment: Asse...,ChinaIndiaLaosMalaysiaMongoliaPapua New Guinea...,1.223288,1.303414,2.969656,0.403935,3.452114,1.191786,1.972746,2.292788,1.073877,1.925982,2.103354,0.0,0.0
17,BoP: Financial Account: Other Investment: Asse...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,18.797103,-7.150608,75.725355,75.201250,171.085484,-0.750614,-27.545161,-89.068366,-26.783662,-33.436350,-3.984352,0.0,0.0
18,BoP: Financial Account: Other Investment: Asse...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,35.885597,-7.467846,33.123541,10.765772,63.856990,16.736025,35.956153,-35.898022,34.105350,-12.050499,34.333103,0.0,0.0
19,BoP: Financial Account: Other Investment: Asse...,ChinaIndiaSouth KoreaLaosMongoliaPhilippinesTh...,0.178600,0.197600,0.159634,0.584566,0.621900,0.263700,0.030800,0.235100,0.125700,0.163882,0.017290,0.0,0.0
20,BoP: Financial Account: Other Investment: Asse...,CambodiaChinaHong Kong SAR (China)IndonesiaSou...,-63.302439,27.025164,-43.861811,84.100755,10.547329,76.728269,-22.513620,8.251211,-23.067384,42.052411,3.668648,0.0,0.0
21,BoP: Financial Account: Other Investment: Liab...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,9.755877,82.791621,254.062898,140.367778,297.401278,213.194011,144.115831,-114.621513,-29.286862,97.943117,151.925991,0.0,0.0
22,BoP: Financial Account: Other Investment: Liab...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,-82.724616,52.549303,71.159163,128.810799,148.039795,26.963648,1.465521,-50.244463,14.266018,30.964836,35.726659,0.0,0.0
23,BoP: Financial Account: Other Investment: Liab...,ChinaIndiaLaosMalaysiaMongoliaPapua New Guinea...,1.491057,0.646862,1.383838,2.012399,2.495649,1.121359,1.129805,1.417142,0.308528,0.110116,1.518360,0.0,0.0
24,BoP: Financial Account: Other Investment: Liab...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,73.946287,0.784701,65.714987,-26.387625,57.148035,3.805182,38.673334,-12.399815,16.264179,2.392517,50.282352,0.0,0.0
25,BoP: Financial Account: Other Investment: Liab...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,26.152550,-2.847914,54.496477,-7.539794,47.606777,-1.441529,57.094275,-13.716374,39.465103,12.839641,65.024418,0.0,0.0
26,BoP: Financial Account: Other Investment: Liab...,IndiaSouth KoreaLaosMongoliaPhilippinesThailand,0.077500,-0.073700,0.048000,-0.029100,0.095000,-0.049400,-0.086700,-0.070900,-0.109500,-0.098200,-0.104900,0.0,0.0
27,BoP: Financial Account: Other Investment: Liab...,CambodiaChinaIndiaIndonesiaSouth KoreaLaosMala...,0.000100,-0.000024,0.000188,0.000552,-0.001241,79.770472,-0.023481,-0.000741,0.008284,0.024102,0.000000,0.0,0.0
28,BoP: Financial Account: Other Investment: Liab...,CambodiaChinaHong Kong SAR (China)IndiaIndones...,-47.535037,16.218312,-45.152834,54.404131,23.199691,40.296621,-4.272471,-8.472214,-53.499534,26.766396,-26.262008,0.0,0.0
29,BoP: Financial Account: Portfolio Investment: ...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,185.591772,128.437818,122.539838,224.208631,251.077490,159.808843,179.940189,191.270011,163.804309,134.303524,335.945596,0.0,0.0
30,BoP: Financial Account: Portfolio Investment: ...,BruneiCambodiaChinaHong Kong SAR (China)Indone...,75.594704,26.797305,28.155688,2.185892,24.288571,35.098850,62.629724,98.762447,69.916290,23.096259,135.147732,0.0,0.0
31,BoP: Financial Account: Portfolio Investment: ...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,32.546366,65.602689,78.339804,181.139651,181.486367,85.883596,66.717666,56.581947,51.835136,53.185865,133.210099,0.0,0.0
32,BoP: Financial Account: Portfolio Investment: ...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,129.367342,103.190326,25.171631,237.717353,158.020092,122.458890,-87.114460,9.693024,25.660934,64.902973,127.015454,0.0,0.0
33,BoP: Financial Account: Portfolio Investment: ...,BruneiChinaHong Kong SAR (China)IndiaIndonesia...,93.912130,68.341268,47.641173,155.382780,121.497116,74.554721,-80.844018,-56.903351,-15.899403,68.068166,101.443795,0.0,0.0
34,BoP: Financial Account: Portfolio Investment: ...,BruneiCambodiaChinaHong Kong SAR (China)IndiaI...,27.711469,33.413830,-18.333166,82.996145,33.050912,41.079127,-12.818670,45.666617,48.759894,-13.333327,13.798242,0.0,0.0

In [52]:
len(df_col)

26