In [9]:
from pathlib import Path
import pandas as pd

path1 = "test.xlsx"
path2 = "financial stress index.xlsx"
path3 = "section 2.xlsx"
path4 = "Automation.xlsx"

df_init = pd.read_excel(path4, sheet_name='BoP edit')
short_title = df_init['short_title'].to_list()
description = df_init['desc'].to_list()
sc2_half = pd.read_excel(path3, sheet_name="sc2_half")
sc2_quarter = pd.read_excel(path3, sheet_name="sc2_quarter")
date_temp = sc2_quarter.columns[4:].to_list()
date_temp2 = [dt.strftime("%Y-%m") for dt in date_temp]
rename_date = {k: v for k, v in zip(date_temp, date_temp2)}
sc2_quarter.rename(columns=rename_date, inplace=True)
sc2_quarter[list(rename_date.values())] = sc2_quarter[list(rename_date.values())].apply(lambda x: round(x, 2))
sc2_quarter['Last Update Time'] = pd.to_datetime(sc2_quarter['Last Update Time']).dt.strftime("%Y-%m-%d")
sc2_quarter['Type'] = sc2_quarter['Type'].replace(description, short_title)
sc2_half[sc2_half.columns[2:]] = sc2_half[sc2_half.columns[2:]].apply(lambda x: round(x,2))
sc2_half['Type'] = sc2_half['Type'].replace(description, short_title)

dict1 = df_init[['group', 'short_title']].groupby("group")["short_title"].apply(list).reset_index().to_dict(orient='list')
dict2 = {k: {item: item for item in v} for k, v in zip(dict1['group'], dict1['short_title'])}

df_main = pd.read_excel(path3, sheet_name="df_main")
df_main[df_main.columns[3:]] = df_main[df_main.columns[3:]].apply(lambda x: round(x,2))

# return sc2_half, sc2_quarter, dict2, df_main

dict2
# return sc2_half, sc2_quarter, dict2, df_main

{'Current Account': {'Current Account': 'Current Account',
  'Trade Balance (Goods)': 'Trade Balance (Goods)',
  'Trade Balance (Services)': 'Trade Balance (Services)',
  'Investment Income': 'Investment Income',
  'Current Transfers': 'Current Transfers'},
 'FDI Assets': {'FDI Assets': 'FDI Assets',
  'FDI Equity Assets': 'FDI Equity Assets',
  'FDI Debt Assets': 'FDI Debt Assets'},
 'FDI Liabilities': {'FDI Liabilities': 'FDI Liabilities',
  'FDI Equity Liabilities': 'FDI Equity Liabilities',
  'FDI Debt Liabilities': 'FDI Debt Liabilities'},
 'Financial Derivative Assets': {'Financial Derivative Assets': 'Financial Derivative Assets'},
 'Financial Derivative Liabilities': {'Financial Derivative Liabilities': 'Financial Derivative Liabilities'},
 'Official Reserve Assets': {'Official Reserve Assets': 'Official Reserve Assets'},
 'Other Investment Assets': {'Other Investment Assets': 'Other Investment Assets',
  'OI Equity Assets': 'OI Equity Assets',
  'Currency and Deposits Assets': 'Currency and Deposits Assets',
  'Loans Assets': 'Loans Assets',
  'Insurance and Pension Assets': 'Insurance and Pension Assets',
  'Trade Credits and Advances Assets': 'Trade Credits and Advances Assets',
  'OI Others Assets': 'OI Others Assets'},
 'Other Investment Liabilities': {'Other Investment Liabilities': 'Other Investment Liabilities',
  'OI Equity Liabilities': 'OI Equity Liabilities',
  'Currency and Deposits Liabilities': 'Currency and Deposits Liabilities',
  'Loans Liabilities': 'Loans Liabilities',
  'Insurance and Pension Liabilities': 'Insurance and Pension Liabilities',
  'Trade Credits and Advances Liabilities': 'Trade Credits and Advances Liabilities',
  'OI Others Liabilities': 'OI Others Liabilities',
  'SDR Liabilities': 'SDR Liabilities'},
 'Portfolio Assets': {'Portfolio Assets': 'Portfolio Assets',
  'Portfolio Equity Assets': 'Portfolio Equity Assets',
  'Portfolio Debt Assets': 'Portfolio Debt Assets'},
 'Portfolio Liabilities': {'Portfolio Liabilities': 'Portfolio Liabilities',
  'Portfolio Equity Liabilities': 'Portfolio Equity Liabilities',
  'Portfolio Debt Liabilities': 'Portfolio Debt Liabilities'}}

In [4]:
sc2_quarter

                             Type                 Region  ... 2025-06 2025-09
0                 Current Account                 Brunei  ...     NaN     NaN
1                 Current Account               Cambodia  ...     NaN     NaN
2                 Current Account                  China  ...     NaN     NaN
3                 Current Account  Hong Kong SAR (China)  ...     NaN     NaN
4                 Current Account                  India  ...     NaN     NaN
..                            ...                    ...  ...     ...     ...
660  Portfolio Equity Liabilities            South Korea  ...     NaN     NaN
661  Portfolio Equity Liabilities              Sri Lanka  ...     NaN     NaN
662  Portfolio Equity Liabilities                 Taiwan  ...     NaN     NaN
663  Portfolio Equity Liabilities               Thailand  ...     NaN     NaN
664  Portfolio Equity Liabilities                Vietnam  ...     NaN     NaN

[665 rows x 31 columns]

In [5]:
df_main

               Group                     Type  ... 2H2024  1H2025
0             Assets        Direct Investment  ...      0       0
1             Assets         Portfolio Equity  ...      0       0
2             Assets           Portfolio Debt  ...      0       0
3             Assets    Financial Derivatives  ...      0       0
4             Assets      Currency & Deposits  ...      0       0
..               ...                      ...  ...    ...     ...
114  Current Account              Goods Trade  ...      0       0
115  Current Account           Services Trade  ...      0       0
116  Current Account           Primary Income  ...      0       0
117  Current Account         Secondary Income  ...      0       0
118  Current Account  Current Account Balance  ...      0       0

[119 rows x 16 columns]