In [ ]:
# youtube - https://www.youtube.com/watch?v=zCEJurLGFRk&t=14s
# % pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib gspread
import gspread
from google.oauth2.service_account import Credentials
import pandas as pd
from gspread_dataframe import set_with_dataframe

from data import Data
from cache_pandas import timed_lru_cache
import logging

@timed_lru_cache(seconds=None, maxsize=None)
def dataF():
    logging.info("Fetching data in dataF()")
    df = Data()
    vix_data = df.vix_history()
    policy_rate1, policy_rate2, policy_rate3 = df.policy_rate()
    fx = df.forex_exchange()
    cds = df.cds()
    liquidity = df.liquidity()
    gdp_growth = df.gdp_growth()
    logging.info("Completed fetching data in dataF()")
    return (
        vix_data, #use this
        policy_rate1, #use this
        policy_rate2,
        policy_rate3,
        fx, #use this
        cds, #use this
        liquidity, #use this
        gdp_growth, #use this
    )


vix2, policy_rate12, policy_rate22, policy_rate32, fx2, cds2, liquidity2, gdp_growth2, = dataF()

scopes = [
    'https://www.googleapis.com/auth/spreadsheets']

creds = Credentials.from_service_account_file(
    'credential.json', scopes=scopes)

client = gspread.authorize(creds)

# 1PP6gpBcoOHjjgCx7LuHLa3dv4ET6ufKvpSY4UDvBczQ
sheet_id = '11Ora6_5EoQJdgnUpjjZgFZyrILguo1c32mde_uQwupw'
sheet = client.open_by_key(sheet_id)

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 40]
})

set_with_dataframe(sheet.sheet1, df) 

values_list = sheet.sheet1.get_all_values()
print(values_list)

worksheet_list = map(lambda x: x.title, sheet.worksheets())
worksheet_name = {'vix_data': vix_data, 'policy_rate1': policy_rate1, 'fx': fx, 'cds': cds, 'liquidity': liquidity, 'gdp_growth': gdp_growth}
for new_worksheet_name, data in worksheet_name.items():
    if new_worksheet_name in worksheet_list:
        sheet1 = sheet.worksheet(new_worksheet_name)
    else:
        sheet1 = sheet.add_worksheet(title=new_worksheet_name, rows=10, cols=10)
    set_with_dataframe(sheet1, data)

# sheet.worksheet(new_worksheet_name) -- to select worksheet page
# sheet.add_worksheet(new_worksheet_name, rows=10, cols=10) -- add new worksheet page

c:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\cfm-nlp\data.py:161: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"]) + pd.offsets.MonthEnd(0)
c:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\cfm-nlp\data.py:296: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2["Date"] = pd.to_datetime(df2["Date"]) + pd.offsets.MonthEnd(0)
c:\USERS\AHMADAIZUDEEN\ONEDRIVE - THE SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\DESKTOP\NLP PROJECT\VENC\Lib\site-packages\pandas\core\indexes\base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)
c:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\cfm-nlp\data.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["Date"] = list(

[['Name', 'Age'], ['Alice', '25'], ['Bob', '30'], ['Charlie', '40']]

In [ ]:
# 
# Loop through worksheet names and data
for new_worksheet_name, data in worksheet_name.items():
    if new_worksheet_name in worksheet_list:
        sheet = spreadsheet.worksheet(new_worksheet_name)  # Select existing worksheet
    else:
        sheet = spreadsheet.add_worksheet(title=new_worksheet_name, rows=10, cols=10)  # ✅ Use 'spreadsheet' object
    
    # Upload DataFrame to Google Sheets
    set_with_dataframe(sheet, data)

print("All data uploaded successfully!")

AttributeError: 'Worksheet' object has no attribute 'add_worksheet'

In [124]:
import pandas as pd 

yield_data1 = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\00 dlx.xlsx", header=1)
yield_data1 = yield_data1[[*yield_data1.columns[[0,1,3]]]]
yield_data1.drop([0,1,2], inplace=True)
yield_data1.rename(columns={'.DESC': 'Date',
                          'Indonesia: 10 Year Treasury Bond Mid Yield (% p.a.)': 'Indonesia',
                          'Philippines: 10 Year Treasury Bond Mid Yield (% p.a.)': 'Philippines'},
                    inplace=True)

# yield_data1["Date"] = pd.to_datetime(yield_data1["Date"], errors='coerce') + pd.offsets.MonthEnd(0)
yield_data1['Month'] = yield_data1['Date'].apply(lambda x: x[:3])
yield_data1['Year'] = yield_data1['Date'].apply(lambda x: x[-2:])
yield_data1["Date"] = yield_data1.apply(lambda x: pd.to_datetime(f"{x['Month']} {x['Year']}", format='%b %y') + pd.offsets.MonthEnd(0), axis=1)
yield_data1.drop(['Month', 'Year'], axis=1, inplace=True)
yield_data2 = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Capital Flow Monitor\SEACEN CFM January 2025\edited files\Data\Financial Stress Indices.xlsx"
                            , sheet_name='Yields2'
                            , header=1)
yield_data2=yield_data2[yield_data2.columns[:11]]
yield_data2.drop([0,1], inplace=True)
yield_data2.rename(columns={'Region': 'Date'}, inplace=True)
yield_data2["Date"] = pd.to_datetime(yield_data2["Date"]) + pd.offsets.MonthEnd(0)
yield_data2.drop('Philippines', axis=1, inplace=True)

yield_data = yield_data2.join(yield_data1.set_index('Date'), on='Date')
yield_data.set_index('Date', inplace=True)

yield_data_calc = yield_data.apply(lambda x : x - x['United States'], axis =1)
yield_data_calc.drop('United States', axis=1, inplace=True)
yield_data_calc = yield_data_calc.loc[yield_data_calc.index >= "2010-01-31"]
yield_data_calc['Asia'] = yield_data_calc.mean(axis= 1)
yield_data_calc = (yield_data_calc - yield_data_calc.mean()) / yield_data_calc.std()
yield_data_calc

,Thailand,Taiwan,Singapore,South Korea,Malaysia,India,Hong Kong SAR (China),China,Indonesia,Philippines,Asia
Date,,,,,,,,,,,
2010-01-31,0.175651,-1.158241,-1.901368,1.572966,-1.004538,-1.107842,-1.050142,-0.741576,NaN,NaN,-1.540744
2010-02-28,0.087742,-1.236897,-1.485320,1.555688,-0.980961,-0.798749,-1.246005,-0.869708,NaN,NaN,-1.505457
2010-03-31,0.046732,-1.259095,-1.260817,1.023806,-1.166129,-0.865235,-1.426455,-0.900146,NaN,NaN,-1.638070
2010-04-30,-0.370188,-1.407762,-1.865981,0.854675,-1.463067,-1.028513,-1.546308,-1.064175,NaN,NaN,-1.940724
2010-05-31,-0.012640,-0.936574,-0.681719,1.458693,-0.888538,-0.862325,-1.134185,-0.777569,NaN,NaN,-1.390754
...,...,...,...,...,...,...,...,...,...,...,...
2024-07-31,-2.132792,-1.681953,-2.281407,-1.879522,-2.484187,-2.197072,-2.174949,-2.542791,-1.683475,-0.423165,-2.454110
2024-08-31,-1.785504,-1.277460,-1.831526,-1.619181,-1.911162,-1.901352,-1.637959,-2.191315,-1.594144,-0.228112,-2.039476
2024-09-30,-1.675572,-1.240222,-1.707193,-1.427541,-1.779653,-1.885661,-1.585829,-2.078945,-1.606654,-0.250560,-1.949901
2024-10-31,-2.151773,-1.636872,-2.079600,-1.824537,-1.995994,-2.183309,-1.589058,-2.409029,-1.809684,-0.877737,-2.402629
2024-11-30,-2.490718,-1.990564,-2.816674,-2.228031,-2.520235,-2.488375,-2.013078,-2.748262,-1.900594,-0.946042,-2.820741

In [115]:
yield_data.loc[yield_data.index >= "2010-01-31"].head(30)

,United States,Thailand,Taiwan,Singapore,South Korea,Malaysia,India,Hong Kong SAR (China),China,Indonesia,Philippines
Date,,,,,,,,,,,
2010-01-31,3.733158,4.17,1.51,2.54,5.3535,4.282,7.5814,2.932,3.6986,NaN,NaN
2010-02-28,3.691053,4.05,1.41,2.69,5.297895,4.257,7.857,2.832,3.5111,NaN,NaN
2010-03-31,3.727391,4.05,1.43,2.83,4.918636,4.159,7.825,2.815,3.5129,NaN,NaN
2010-04-30,3.846818,3.8,1.44,2.67,4.905909,4.063,7.7766,2.899,3.4462,NaN,NaN
2010-05-31,3.42,3.69,1.36,2.79,4.951053,4.053,7.5206,2.594,3.3446,NaN,NaN
2010-06-30,3.204091,3.42,1.44,2.37,4.934762,3.957,7.5758,2.336,3.3979,NaN,NaN
2010-07-31,3.011429,3.41,1.4,1.95,4.907727,3.918,7.8286,2.251,3.3357,NaN,NaN
2010-08-31,2.698636,3.31,1.24,1.99,4.676364,3.714,7.9863,1.992,3.3021,NaN,NaN
2010-09-30,2.647619,3.1,1.21,2.02,4.28,3.625,7.8963,2.057,3.4047,7.907477,NaN
2010-10-31,2.54,3.03,1.19,1.98,4.105238,3.861,8.1179,2.161,3.7546,7.242381,NaN
2010-11-30,2.763,3.48,1.39,2.29,4.483636,3.825,8.0498,2.419,4.0867,7.433932,NaN
2010-12-31,3.290909,3.74,1.47,2.71,4.45913,4.038,7.9534,2.778,3.9017,7.555478,NaN
2011-01-31,3.394,3.79,1.45,2.57,4.694286,4.059,8.1505,2.687,4.0802,8.408905,NaN
2011-02-28,3.576316,3.88,1.4,2.6,4.764118,4.066,8.0983,2.674,3.9785,8.815025,NaN
2011-03-31,3.414348,3.83,1.38,2.48,4.511364,4.101,8.0223,2.552,3.9788,8.318391,NaN
2011-04-30,3.455,3.72,1.36,2.41,4.481905,4.032,8.1267,2.43,3.9465,7.741667,NaN
2011-05-31,3.168571,3.79,1.44,2.39,4.3385,4.004,8.4123,2.273,3.908,7.571386,NaN
2011-06-30,3.002273,3.8,1.49,2.31,4.242857,3.929,8.3518,2.064,3.9939,7.408909,NaN
2011-07-31,3.003,4.01,1.51,2.02,4.229524,3.877,8.4792,2.034,4.0985,7.24531,NaN
2011-08-31,2.303043,3.6,1.4,1.64,3.960909,3.644,8.3543,1.739,4.1258,6.887609,NaN
2011-09-30,1.975238,3.68,1.26,1.62,3.754,3.702,8.3975,1.309,3.8537,6.948182,5.852727
2011-10-31,2.152,3.51,1.29,1.75,3.855,3.75,8.8849,1.506,3.8166,6.466429,5.83119
2011-11-30,2.0135,3.43,1.32,1.68,3.802727,3.748,8.7594,1.353,3.6804,6.356136,5.725682
2011-12-31,1.978095,3.28,1.27,1.63,3.811364,3.699,8.5459,1.55,3.4763,6.126136,5.376932
2012-01-31,1.9665,3.23,1.29,1.54,3.7955,3.557,8.2878,1.648,3.4291,5.8125,5.165909
2012-02-29,1.9675,3.33,1.27,1.48,3.814286,3.457,8.2,1.603,3.5777,5.177857,4.947619
2012-03-31,2.172727,3.69,1.27,1.66,3.952381,3.678,8.5607,1.614,3.5465,5.788409,5.210682
2012-04-30,2.052857,3.82,1.28,1.55,3.8975,3.576,8.6523,1.489,3.5826,5.907619,5.31119
2012-05-31,1.803182,3.82,1.23,1.46,3.749048,3.558,8.4599,1.356,3.4423,6.295217,5.357826
2012-06-30,1.622381,3.62,1.2,1.61,3.6305,3.516,8.2269,1.241,3.3846,6.313571,5.390952

In [123]:
yield_data_calc = yield_data.apply(lambda x : x - x['United States'], axis =1)
yield_data_calc.drop('United States', axis=1, inplace=True)
yield_data_calc = yield_data_calc.loc[yield_data_calc.index >= "2010-01-31"]
yield_data_calc['Asia'] = yield_data_calc.mean(axis= 1)
yield_data_calc = (yield_data_calc - yield_data_calc.mean()) / yield_data_calc.std()
yield_data_calc

,Thailand,Taiwan,Singapore,South Korea,Malaysia,India,Hong Kong SAR (China),China,Indonesia,Philippines,Asia
Date,,,,,,,,,,,
2010-01-31,0.175651,-1.158241,-1.901368,1.572966,-1.004538,-1.107842,-1.050142,-0.741576,NaN,NaN,-1.540744
2010-02-28,0.087742,-1.236897,-1.485320,1.555688,-0.980961,-0.798749,-1.246005,-0.869708,NaN,NaN,-1.505457
2010-03-31,0.046732,-1.259095,-1.260817,1.023806,-1.166129,-0.865235,-1.426455,-0.900146,NaN,NaN,-1.638070
2010-04-30,-0.370188,-1.407762,-1.865981,0.854675,-1.463067,-1.028513,-1.546308,-1.064175,NaN,NaN,-1.940724
2010-05-31,-0.012640,-0.936574,-0.681719,1.458693,-0.888538,-0.862325,-1.134185,-0.777569,NaN,NaN,-1.390754
...,...,...,...,...,...,...,...,...,...,...,...
2024-07-31,-2.132792,-1.681953,-2.281407,-1.879522,-2.484187,-2.197072,-2.174949,-2.542791,-1.683475,-0.423165,-2.454110
2024-08-31,-1.785504,-1.277460,-1.831526,-1.619181,-1.911162,-1.901352,-1.637959,-2.191315,-1.594144,-0.228112,-2.039476
2024-09-30,-1.675572,-1.240222,-1.707193,-1.427541,-1.779653,-1.885661,-1.585829,-2.078945,-1.606654,-0.250560,-1.949901
2024-10-31,-2.151773,-1.636872,-2.079600,-1.824537,-1.995994,-2.183309,-1.589058,-2.409029,-1.809684,-0.877737,-2.402629
2024-11-30,-2.490718,-1.990564,-2.816674,-2.228031,-2.520235,-2.488375,-2.013078,-2.748262,-1.900594,-0.946042,-2.820741

In [36]:
# https://www.seacen.org/publication-working.php?pid=702001-100492 -- kene search
# https://www.seacen.org/publications/RePEc/702001-100492-PDF.pdf -- word

ks = r'https://www.seacen.org/publication-working.php?pid='
wd_list = ['https://www.seacen.org/publications/RePEc/702001-100492-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100483-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100482-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100480-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100471-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100461-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100449-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100444-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-0-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100430-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100427-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100417-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100413-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100402-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100388-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100378-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100334-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100070-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100074-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100071-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100300-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702001-100242-PDF.pdf',
           'https://www.seacen.org/publications/RePEc/702004-100259-PDF.pdf'
           ,
           ]

ks.split('=')[-1]

''

In [38]:
list1 = []
for wd in wd_list:
    wdl = wd.split('/')[-1].split('.')[0].split('-')[:2]
    id = '-'.join(wdl)
    link = ks + id
    list1.append(link)
# ks1 = ks.split('=')[0]
# tuple(zip(id, ks1))

In [39]:
list1

['https://www.seacen.org/publication-working.php?pid=702001-100492',
 'https://www.seacen.org/publication-working.php?pid=702001-100483',
 'https://www.seacen.org/publication-working.php?pid=702001-100482',
 'https://www.seacen.org/publication-working.php?pid=702001-100480',
 'https://www.seacen.org/publication-working.php?pid=702001-100471',
 'https://www.seacen.org/publication-working.php?pid=702001-100461',
 'https://www.seacen.org/publication-working.php?pid=702001-100449',
 'https://www.seacen.org/publication-working.php?pid=702001-100444',
 'https://www.seacen.org/publication-working.php?pid=702001-0',
 'https://www.seacen.org/publication-working.php?pid=702001-100430',
 'https://www.seacen.org/publication-working.php?pid=702001-100427',
 'https://www.seacen.org/publication-working.php?pid=702001-100417',
 'https://www.seacen.org/publication-working.php?pid=702001-100413',
 'https://www.seacen.org/publication-working.php?pid=702001-100402',
 'https://www.seacen.org/publication-working.php?pid=702001-100388',
 'https://www.seacen.org/publication-working.php?pid=702001-100378',
 'https://www.seacen.org/publication-working.php?pid=702001-100334',
 'https://www.seacen.org/publication-working.php?pid=702001-100070',
 'https://www.seacen.org/publication-working.php?pid=702001-100074',
 'https://www.seacen.org/publication-working.php?pid=702001-100071',
 'https://www.seacen.org/publication-working.php?pid=702001-100300',
 'https://www.seacen.org/publication-working.php?pid=702001-100242',
 'https://www.seacen.org/publication-working.php?pid=702004-100259']

In [40]:
import requests as r
for x in list1:
    response = r.get(x)
    print(response.status_code)

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

In [ ]:
print(len(list1))
print(len(set(list1))) 
#no duplicate

23
23