In [131]:
import pandas as pd

df = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Capital Flow Monitor\SEACEN CFM January 2025\edited files\Data\Growth and Inflation 3Q2024.xlsx"
                   , sheet_name=1
                   , header=1)
df.head()

,Region,China,Hong Kong SAR (China),India,Indonesia,South Korea,Malaysia,Mongolia,Philippines,Singapore,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Unit,Prev Year=100,%,INR mn,%,%,MYR mn,MNT mn,PHP mn,%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Update Time,2024-10-18 00:00:00,2024-10-31 00:00:00,2024-11-29 00:00:00,2024-11-05 00:00:00,2024-12-18 00:00:00,2024-11-15 00:00:00,2024-11-18 00:00:00,2024-11-07 00:00:00,2024-11-22 00:00:00,...,India,Indonesia,South Korea,Malaysia,Mongolia,Philippines,Singapore,Taiwan,Thailand,Vietnam
2,2000-03-01 00:00:00,108.7,10.7,NaN,NaN,12.6,NaN,NaN,1653296.013866,9,...,NaN,NaN,12.6,NaN,NaN,NaN,9,NaN,NaN,NaN
3,2000-06-01 00:00:00,108.9,7.4,NaN,NaN,9.2,NaN,NaN,1729789.409909,8.2,...,NaN,NaN,9.2,NaN,NaN,NaN,8.2,NaN,NaN,NaN
4,2000-09-01 00:00:00,108.9,7.2,NaN,NaN,9.3,NaN,NaN,1709412.902916,9.5,...,NaN,NaN,9.3,NaN,NaN,NaN,9.5,NaN,NaN,NaN

In [169]:
df2 = df.copy()
df2 = df2.drop([0,1], axis=0)
df2 = df2[df2.columns[:13]].rename(columns={'Region':'Date'}).set_index('Date')
df3 = df2[['India', 'Malaysia', 'Mongolia', 'Philippines', 'Taiwan', 'Thailand']].apply(lambda x : ((x/x.shift(4)) - 1)*100)
df3 = pd.concat([df2[['China', 'Hong Kong SAR (China)', 'Indonesia', 'South Korea', 'Singapore', 'Vietnam']], df3], axis=1)
df3.reset_index(inplace=True)
df3["Date"] = pd.to_datetime(df3["Date"]) + pd.offsets.MonthEnd(0)
select_row = len(fd.columns) - 1 
df4 = df3[-select_row:]
def convert_date_to_quarter(date_str):
    year = date_str[:4]
    quarter = date_str[5:7]
    if quarter == '03':
        return f"1Q{year}"
    elif quarter == '06':
        return f"2Q{year}"
    elif quarter == '09':
        return f"3Q{year}"
    elif quarter == '12':
        return f"4Q{year}"
    else:
        return date_str

df4['Date'] = list(df4['Date'].apply(lambda x: convert_date_to_quarter(str(x))))
df4 = df4.set_index('Date').transpose().reset_index().rename(columns={'index':'Region'})
df4

c:\USERS\AHMADAIZUDEEN\ONEDRIVE - THE SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\DESKTOP\NLP PROJECT\VENC\Lib\site-packages\pandas\core\indexes\base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)
C:\Users\AhmadAizudeen\AppData\Local\Temp\ipykernel_22716\3717174941.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Date'] = list(df4['Date'].apply(lambda x: convert_date_to_quarter(str(x))))

Date,Region,1Q2022,2Q2022,3Q2022,4Q2022,1Q2023,2Q2023,3Q2023,4Q2023,1Q2024,2Q2024,3Q2024
0,China,104.8,102.5,103,102.95067,104.6,105.5,105.2,105.249558,105.3,105,104.8
1,Hong Kong SAR (China),-4,-1.5,-4.9,-4.3,2.8,1.6,4.2,4.3,2.8,3.2,1.8
2,Indonesia,5.02477,5.458804,5.731697,5.006646,5.043991,5.174841,4.938607,5.03708,5.114813,5.045594,4.947227
3,South Korea,3.5,3,3.4,1.1,1.1,1,1.4,2.1,3.3,2.3,1.5
4,Singapore,4.2,4.6,4.2,2.4,0.5,0.5,1,2.2,3,3,5.4
5,Vietnam,5.12,7.99,13.714433,5.96,3.41,4.25,5.47,6.723794,5.873694,6.93,7.404853
6,India,4.452846,12.809867,5.457394,4.257832,6.180254,8.241616,8.07987,8.569857,7.757278,6.654026,5.364436
7,Malaysia,5.100228,8.858634,14.361344,7.351491,5.511463,2.785735,3.119313,2.915081,4.230259,5.910764,5.340809
8,Mongolia,-2.450518,1.834313,7.439896,11.212856,7.884944,4.920212,8.822867,7.158264,7.960038,3.850064,3.504364
9,Philippines,8.072153,7.520952,7.701549,7.129328,6.428306,4.305533,6.003783,5.534721,5.7577,6.395073,5.219006
10,Taiwan,3.848059,3.513133,4.060482,-0.430033,-3.468238,1.469971,1.553703,4.730491,6.639563,4.885464,4.166068
11,Thailand,1.939086,2.426366,4.408484,1.282915,2.611044,1.751541,1.423128,1.717235,1.636125,2.225235,2.959167

In [167]:
fd

,Region,1Q2022,2Q2022,3Q2022,4Q2022,1Q2023,2Q2023,3Q2023,4Q2023,1Q2024,2Q2024,3Q2024
0,China,31678.065,31678.065,31678.065,31678.065,34540.882,34540.882,34540.882,34540.882,37072.086,37072.086,37072.086
1,Hong Kong,503.959,503.959,503.959,503.959,539.201,539.201,539.201,539.201,569.828,569.828,569.828
2,India,13048.142,13048.142,13048.142,13048.142,14619.782,14619.782,14619.782,14619.782,16019.970,16019.970,16019.970
3,Indonesia,3983.080,3983.080,3983.080,3983.080,4334.721,4334.721,4334.721,4334.721,4658.321,4658.321,4658.321
4,Korea,2955.787,2955.787,2955.787,2955.787,3105.151,3105.151,3105.151,3105.151,3258.366,3258.366,3258.366
5,Malaysia,1192.355,1192.355,1192.355,1192.355,1279.182,1279.182,1279.182,1279.182,1372.610,1372.610,1372.610
6,Mongolia,56.320,56.320,56.320,56.320,62.678,62.678,62.678,62.678,67.691,67.691,67.691
7,Philippines,1154.611,1154.611,1154.611,1154.611,1262.499,1262.499,1262.499,1262.499,1367.043,1367.043,1367.043
8,Singapore,799.968,799.968,799.968,799.968,837.665,837.665,837.665,837.665,879.978,879.978,879.978
9,Taipei,1653.793,1653.793,1653.793,1653.793,1735.226,1735.226,1735.226,1735.226,1843.016,1843.016,1843.016
10,Thailand,1594.739,1594.739,1594.739,1594.739,1683.069,1683.069,1683.069,1683.069,1771.532,1771.532,1771.532
11,Vietnam,1380.787,1380.787,1380.787,1380.787,1502.664,1502.664,1502.664,1502.664,1631.796,1631.796,1631.796
12,SUM,60001.606,60001.606,60001.606,60001.606,65502.720,65502.720,65502.720,65502.720,70512.237,70512.237,70512.237

In [134]:
df3.reset_index(inplace=True)
df3["Date"] = pd.to_datetime(df3["Date"]) + pd.offsets.MonthEnd(0)
df3

,Date,China,Hong Kong SAR (China),Indonesia,South Korea,Singapore,Vietnam,India,Malaysia,Mongolia,Philippines,Taiwan,Thailand
0,2000-03-31,108.7,10.7,NaN,12.6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-06-30,108.9,7.4,NaN,9.2,8.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-09-30,108.9,7.2,NaN,9.3,9.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-12-31,108.490093,5.7,NaN,6.2,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2001-03-31,109.5,2,NaN,5,5.4,NaN,NaN,NaN,NaN,2.414137,1.452775,2.325661
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023-09-30,105.2,4.2,4.938607,1.4,1,5.47,8.07987,3.119313,8.822867,6.003783,1.553703,1.423128
95,2023-12-31,105.249558,4.3,5.03708,2.1,2.2,6.723794,8.569857,2.915081,7.158264,5.534721,4.730491,1.717235
96,2024-03-31,105.3,2.8,5.114813,3.3,3,5.873694,7.757278,4.230259,7.960038,5.7577,6.639563,1.636125
97,2024-06-30,105,3.2,5.045594,2.3,3,6.93,6.654026,5.910764,3.850064,6.395073,4.885464,2.225235
98,2024-09-30,104.8,1.8,4.947227,1.5,5.4,7.404853,5.364436,5.340809,3.504364,5.219006,4.166068,2.959167

In [85]:
fd = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Capital Flow Monitor\SEACEN CFM January 2025\edited files\Data\Growth and Inflation 3Q2024.xlsx"
                   , sheet_name=2, nrows=13)

# fd = fd[fd.columns[:12]]
def convert_quarter_to_date(quarter_str):
    year = quarter_str[-4:]
    quarter = quarter_str[0]
    if quarter == '1':
        return f"31/3/{year}"
    elif quarter == '2':
        return f"30/6/{year}"
    elif quarter == '3':
        return f"30/9/{year}"
    elif quarter == '4':
        return f"31/12/{year}"
    else:
        return quarter_str

col_name = list(map(convert_quarter_to_date,fd.columns))
# fd.rename(columns=dict(zip(fd.columns, col_name)), inplace=True) #might not need
fd.fillna('SUM', inplace=True)
fd.rename({fd.columns[0]: 'Region'}, axis=1, inplace=True)

In [135]:
select_row = len(fd.columns) - 1 
df4 = df3[-select_row:]
df4

,Date,China,Hong Kong SAR (China),Indonesia,South Korea,Singapore,Vietnam,India,Malaysia,Mongolia,Philippines,Taiwan,Thailand
88,2022-03-31,104.8,-4,5.02477,3.5,4.2,5.12,4.452846,5.100228,-2.450518,8.072153,3.848059,1.939086
89,2022-06-30,102.5,-1.5,5.458804,3,4.6,7.99,12.809867,8.858634,1.834313,7.520952,3.513133,2.426366
90,2022-09-30,103,-4.9,5.731697,3.4,4.2,13.714433,5.457394,14.361344,7.439896,7.701549,4.060482,4.408484
91,2022-12-31,102.95067,-4.3,5.006646,1.1,2.4,5.96,4.257832,7.351491,11.212856,7.129328,-0.430033,1.282915
92,2023-03-31,104.6,2.8,5.043991,1.1,0.5,3.41,6.180254,5.511463,7.884944,6.428306,-3.468238,2.611044
93,2023-06-30,105.5,1.6,5.174841,1,0.5,4.25,8.241616,2.785735,4.920212,4.305533,1.469971,1.751541
94,2023-09-30,105.2,4.2,4.938607,1.4,1,5.47,8.07987,3.119313,8.822867,6.003783,1.553703,1.423128
95,2023-12-31,105.249558,4.3,5.03708,2.1,2.2,6.723794,8.569857,2.915081,7.158264,5.534721,4.730491,1.717235
96,2024-03-31,105.3,2.8,5.114813,3.3,3,5.873694,7.757278,4.230259,7.960038,5.7577,6.639563,1.636125
97,2024-06-30,105,3.2,5.045594,2.3,3,6.93,6.654026,5.910764,3.850064,6.395073,4.885464,2.225235
98,2024-09-30,104.8,1.8,4.947227,1.5,5.4,7.404853,5.364436,5.340809,3.504364,5.219006,4.166068,2.959167

In [144]:
def convert_date_to_quarter(date_str):
    year = date_str[:4]
    quarter = date_str[5:7]
    if quarter == '03':
        return f"1Q{year}"
    elif quarter == '06':
        return f"2Q{year}"
    elif quarter == '09':
        return f"3Q{year}"
    elif quarter == '12':
        return f"4Q{year}"
    else:
        return date_str

df4['Date'] = list(df4['Date'].apply(lambda x: convert_date_to_quarter(str(x))))
df4

C:\Users\AhmadAizudeen\AppData\Local\Temp\ipykernel_22716\3632325476.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Date'] = list(df4['Date'].apply(lambda x: convert_date_to_quarter(str(x))))

,Date,China,Hong Kong SAR (China),Indonesia,South Korea,Singapore,Vietnam,India,Malaysia,Mongolia,Philippines,Taiwan,Thailand
88,1Q2022,104.8,-4,5.02477,3.5,4.2,5.12,4.452846,5.100228,-2.450518,8.072153,3.848059,1.939086
89,2Q2022,102.5,-1.5,5.458804,3,4.6,7.99,12.809867,8.858634,1.834313,7.520952,3.513133,2.426366
90,3Q2022,103,-4.9,5.731697,3.4,4.2,13.714433,5.457394,14.361344,7.439896,7.701549,4.060482,4.408484
91,4Q2022,102.95067,-4.3,5.006646,1.1,2.4,5.96,4.257832,7.351491,11.212856,7.129328,-0.430033,1.282915
92,1Q2023,104.6,2.8,5.043991,1.1,0.5,3.41,6.180254,5.511463,7.884944,6.428306,-3.468238,2.611044
93,2Q2023,105.5,1.6,5.174841,1,0.5,4.25,8.241616,2.785735,4.920212,4.305533,1.469971,1.751541
94,3Q2023,105.2,4.2,4.938607,1.4,1,5.47,8.07987,3.119313,8.822867,6.003783,1.553703,1.423128
95,4Q2023,105.249558,4.3,5.03708,2.1,2.2,6.723794,8.569857,2.915081,7.158264,5.534721,4.730491,1.717235
96,1Q2024,105.3,2.8,5.114813,3.3,3,5.873694,7.757278,4.230259,7.960038,5.7577,6.639563,1.636125
97,2Q2024,105,3.2,5.045594,2.3,3,6.93,6.654026,5.910764,3.850064,6.395073,4.885464,2.225235
98,3Q2024,104.8,1.8,4.947227,1.5,5.4,7.404853,5.364436,5.340809,3.504364,5.219006,4.166068,2.959167

In [ ]:
df4.set_index('Date').transpose().reset_index().rename(columns={'index':'Region'})

Date,Region,1Q2022,2Q2022,3Q2022,4Q2022,1Q2023,2Q2023,3Q2023,4Q2023,1Q2024,2Q2024,3Q2024
0,China,104.8,102.5,103,102.95067,104.6,105.5,105.2,105.249558,105.3,105,104.8
1,Hong Kong SAR (China),-4,-1.5,-4.9,-4.3,2.8,1.6,4.2,4.3,2.8,3.2,1.8
2,Indonesia,5.02477,5.458804,5.731697,5.006646,5.043991,5.174841,4.938607,5.03708,5.114813,5.045594,4.947227
3,South Korea,3.5,3,3.4,1.1,1.1,1,1.4,2.1,3.3,2.3,1.5
4,Singapore,4.2,4.6,4.2,2.4,0.5,0.5,1,2.2,3,3,5.4
5,Vietnam,5.12,7.99,13.714433,5.96,3.41,4.25,5.47,6.723794,5.873694,6.93,7.404853
6,India,4.452846,12.809867,5.457394,4.257832,6.180254,8.241616,8.07987,8.569857,7.757278,6.654026,5.364436
7,Malaysia,5.100228,8.858634,14.361344,7.351491,5.511463,2.785735,3.119313,2.915081,4.230259,5.910764,5.340809
8,Mongolia,-2.450518,1.834313,7.439896,11.212856,7.884944,4.920212,8.822867,7.158264,7.960038,3.850064,3.504364
9,Philippines,8.072153,7.520952,7.701549,7.129328,6.428306,4.305533,6.003783,5.534721,5.7577,6.395073,5.219006
10,Taiwan,3.848059,3.513133,4.060482,-0.430033,-3.468238,1.469971,1.553703,4.730491,6.639563,4.885464,4.166068
11,Thailand,1.939086,2.426366,4.408484,1.282915,2.611044,1.751541,1.423128,1.717235,1.636125,2.225235,2.959167

In [156]:
df4.set_index('Date').transpose()[['1Q2022', '2Q2022']]

Date                     1Q2022     2Q2022
China                     104.8      102.5
Hong Kong SAR (China)        -4       -1.5
Indonesia               5.02477   5.458804
South Korea                 3.5          3
Singapore                   4.2        4.6
Vietnam                    5.12       7.99
India                  4.452846  12.809867
Malaysia               5.100228   8.858634
Mongolia              -2.450518   1.834313
Philippines            8.072153   7.520952
Taiwan                 3.848059   3.513133
Thailand               1.939086   2.426366