In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vladtasca/fomc-meeting-statements-and-minutes", force_download=True)

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/vladtasca/fomc-meeting-statements-and-minutes?dataset_version_number=45...

100%|██████████| 2.91M/2.91M [00:01<00:00, 1.92MB/s]

Extracting files...
Path to dataset files: C:\Users\Admin\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45

In [7]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Admin\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45\communications.csv')
df.head()

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...
2,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
3,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
4,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...

In [8]:
from pandasql import sqldf as sd

sd('select * from df order by "Release Date" desc')

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...
2,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
3,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...
4,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
...,...,...,...,...
436,2001-09-17,None,Minute,Minutes of the Federal Open Market Committee\n...
437,2001-09-13,None,Minute,Minutes of the Federal Open Market Committee\n...
438,2001-04-18,None,Minute,Minutes of the Federal Open Market Committee\n...
439,2001-04-11,None,Minute,Minutes of the Federal Open Market Committee\n...
440,2001-01-03,None,Minute,Minutes of the Federal Open Market Committee\n...

In [9]:
df2 = sd('select * from df where Type = "Statement"')
df2.head()

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
2,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
3,2024-07-31,2024-07-31,Statement,Recent indicators suggest that economic activi...
4,2024-06-12,2024-06-12,Statement,Recent indicators suggest that economic activi...

In [10]:
df.tail()

,Date,Release Date,Type,Text
436,2000-05-16,2000-05-16,Statement,The Federal Open Market Committee voted today ...
437,2000-03-21,2000-05-18,Minute,Minutes of the Federal Open Market Committee\n...
438,2000-03-21,2000-03-21,Statement,The Federal Open Market Committee voted today ...
439,2000-02-02,2000-03-23,Minute,Minutes of the Federal Open Market Committee\n...
440,2000-02-02,2000-02-02,Statement,The Federal Open Market Committee voted today ...

In [11]:
sd('select count(Text) from df where Type = "Minute"')

   count(Text)
0          229

In [12]:
from textblob import TextBlob

def score_sentence_with_textblob(sentence):
    blob = TextBlob(sentence)
    polarity = blob.sentiment.polarity
    return polarity

# Example usage:
sentence = "fuck"
print(score_sentence_with_textblob(sentence))

-0.4

In [15]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

sentence = "It was a good day but with some bad moments."
# tokens = word_tokenize(sentence)
# print(tokens)  # Output: ['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [17]:
nltk.download('punkt_tab')
tokens = word_tokenize(sentence)
print(tokens)  # Output: ['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...

['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

In [104]:
import pandas as pd 

df = pd.read_excel('Aruoba_Drechsel_Data.xlsx', sheet_name='Sentiments overview')
df = df.rename(columns={'Includes (because synonym or closely related)':'Includes', 'Excludes (these are separate sentiments unless they appear infrequently)':'Excludes'})
df['Includes2'] = df.apply(
    lambda row: row['Sentiment label'] + ', ' + row['Includes'] if pd.notna(row['Includes']) else row['Sentiment label'],
    axis=1
)
df.head()

,Sentiment label,Includes,Excludes,Includes2
0,borrowing,borrowers,NaN,"borrowing, borrowers"
1,brazil,brazilian,NaN,"brazil, brazilian"
2,banks,"bank, banking, bankers",district banks,"banks, bank, banking, bankers"
3,canada,canadian,NaN,"canada, canadian"
4,credit,NaN,"credit standards, credit quality",credit

In [102]:
df2 = df[['Includes2', 'Excludes']].map(lambda x: None if str(x).split(', ')[0] == 'nan' else str(x).split(', '))
df2.head()

                         Includes2                            Excludes
0           [borrowing, borrowers]                                None
1              [brazil, brazilian]                                None
2  [banks, bank, banking, bankers]                    [district banks]
3               [canada, canadian]                                None
4                         [credit]  [credit standards, credit quality]

In [140]:
def func():
df2['Includes3'] = df2['Includes2'].map(lambda x : x)

                           Includes2                            Excludes
0             [borrowing, borrowers]                                None
1                [brazil, brazilian]                                None
2    [banks, bank, banking, bankers]                    [district banks]
3                 [canada, canadian]                                None
4                           [credit]  [credit standards, credit quality]
..                               ...                                 ...
291                    [contractors]                                None
292              [corporate profits]                                None
293            [insurance companies]                                None
294                 [wage pressures]                                None
295            [market expectations]                                None

[296 rows x 2 columns]

In [127]:
from nltk.tokenize import RegexpTokenizer
from pandasql import sqldf as sd

fomc = pd.read_csv(r'C:\Users\AhmadAizudeen\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45\communications.csv')
fomc = sd('select * from fomc where Type = "Minute"')
tokenizer = RegexpTokenizer(r'\w+')

fomc['tokenized text'] = fomc['Text'].map(lambda x : tokenizer.tokenize(x.lower()))
fomc.head()

,Date,Release Date,Type,Text,tokenized text
0,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
1,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
2,2024-07-31,2024-08-21,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
3,2024-06-12,2024-07-03,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
4,2024-05-01,2024-05-22,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."

In [133]:
eco_ind = pd.read_excel('Aruoba_Drechsel_Data.xlsx', sheet_name='Sentiments by meeting', index_col=0)
eco_ind.head()

,borrowing,brazil,banks,canada,credit,china,consumption,construction,currencies,deposits,...,russia,workers,economic expansion,economic data,canadian dollar,contractors,corporate profits,insurance companies,wage pressures,market expectations
FOMC meeting (scheduled),,,,,,,,,,,,,,,,,,,,,
1982_10_05,-2.248049,-0.397627,-2.069843,-0.532678,0.339695,0.419825,-1.400883,-1.693100,1.100398,-1.343805,...,0.365198,-1.665561,0.260666,-0.870816,-0.087391,0.219267,-1.865366,0.262187,0.664378,0.459712
1982_11_16,-3.872575,-1.991724,-1.762177,-1.310815,0.287549,0.419825,-1.385852,-1.069244,-0.347396,-1.162794,...,0.365198,-2.961253,0.260666,0.321653,-0.083493,0.219267,-5.187434,-0.690550,0.664378,0.459712
1982_12_21,-2.330907,1.003767,-1.663421,-0.700483,-0.796532,0.419825,0.148721,-1.149710,-1.565683,-1.759771,...,0.365198,0.484308,0.260666,0.321653,1.810921,-0.254227,-2.161714,0.262187,0.664378,0.459712
1983_02_09,-0.358473,0.507433,0.854820,0.282557,0.806648,0.019820,0.568375,0.453294,-0.025795,-2.211075,...,0.365198,-3.789039,-1.923855,0.321653,0.423312,0.219267,-1.764862,1.179239,0.664378,-3.268755
1983_03_29,-0.421778,-0.301260,0.181621,-0.708089,0.814349,0.419825,1.728527,1.667024,0.543804,0.203953,...,0.365198,-0.057465,0.260666,0.321653,0.423312,-1.684726,-1.664541,-1.486045,0.664378,0.459712

In [138]:
len(list(eco_ind.columns))

296

In [17]:
def calc(P=1450, r=0.053, n=30, inc = 114):
    fv = 0
    for x in range(n):
        if fv > 0:
            ttl_month = 12
            P = P + inc
            fv2 = P*(((1+r/12)**ttl_month)-1)/(r/12)
            fv = fv + fv2
        elif fv == 0:
            ttl_month = 12
            fv2 = P*(((1+r/12)**ttl_month)-1)/(r/12)
            fv = fv + fv2
    return fv

calc()

17828.95999276154

In [14]:
total, interest, n, increment = 0, 0, 2, 114
for x in range(n):
    fv = calc()
    total = total + fv
    # interest = interest + y
print(total)

35657.91998552308

In [217]:
import pandas as pd
import datetime

df = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Capital Flow Monitor\SEACEN CFM January 2025\edited files\Data\Growth and Inflation 3Q2024.xlsx", sheet_name=3, nrows=17)
df = df.drop(df.columns[[0,2,3]], axis = 1)
date = df.columns[1:]
date_new =[x for x in date if isinstance(x, datetime.date)]
df = df[['Region', *date_new]]
date2 = [x.date().strftime("%Y-%m") for x in date]
df = df.rename(columns={k:v for (k,v) in zip(date,date2)})
df

,Region,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,...,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11
0,Brunei,99.994630,100.525280,100.832910,101.070210,100.915650,100.950870,100.865250,100.710670,100.812860,...,106.235395,106.343983,106.196367,106.501109,106.611163,106.256769,106.546495,106.248550,105.952130,NaN
1,Cambodia,180.799000,180.654000,181.464000,180.410000,181.563000,182.356000,183.014000,182.788000,183.559000,...,199.123000,200.025000,201.932000,203.546000,203.560000,204.323000,205.332000,206.026000,207.932000,NaN
2,China,105.400000,105.200000,104.300000,103.300000,102.400000,102.500000,102.700000,102.400000,101.700000,...,100.700000,100.100000,100.300000,100.300000,100.200000,100.500000,100.600000,100.400000,100.300000,100.20000
3,Hong Kong SAR (China),98.500000,101.000000,100.900000,101.000000,100.700000,100.600000,97.700000,99.900000,97.800000,...,107.100000,107.100000,106.400000,106.200000,106.700000,107.800000,107.800000,107.900000,108.100000,NaN
4,India,150.200000,149.100000,148.600000,151.400000,150.900000,151.800000,153.900000,154.700000,156.400000,...,185.800000,185.800000,186.700000,187.700000,190.200000,193.000000,193.000000,194.200000,196.800000,196.50000
5,Indonesia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.580000,106.130000,106.400000,106.370000,106.280000,106.090000,106.060000,105.930000,106.010000,106.33000
6,Laos,111.708972,111.474994,111.653164,112.183194,112.386735,112.475465,113.195632,114.838308,115.016946,...,215.949711,218.832317,222.343595,229.276612,234.544075,239.752747,242.492803,245.768117,249.600000,264.27000
7,Malaysia,122.400000,122.400000,120.900000,117.600000,117.900000,119.100000,119.900000,120.100000,120.100000,...,132.100000,132.200000,132.400000,132.800000,133.000000,133.100000,133.200000,133.200000,133.400000,NaN
8,Nepal,132.380000,132.760000,132.400000,133.220000,133.670000,133.540000,134.690000,136.480000,137.620000,...,164.100000,164.580000,166.090000,167.580000,168.090000,168.770000,NaN,NaN,NaN,NaN
9,Philippines,104.500000,104.100000,103.900000,103.800000,103.800000,104.400000,104.900000,104.800000,104.900000,...,125.500000,125.600000,125.500000,125.600000,125.600000,126.500000,126.600000,126.300000,126.500000,127.00000
10,Singapore,100.204000,100.279000,99.933000,99.012000,99.480000,99.500000,99.178000,99.807000,100.139000,...,115.772000,115.662000,115.764000,116.574000,116.323000,116.028000,116.829000,117.123000,116.756000,NaN
11,South Korea,100.090000,100.160000,99.940000,99.500000,99.440000,99.710000,99.630000,100.190000,100.740000,...,113.780000,113.950000,114.010000,114.100000,113.840000,114.130000,114.540000,114.650000,114.690000,114.40000
12,Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,214.500000,210.000000,208.200000,206.300000,208.100000,206.900000,204.100000,203.100000,202.100000,NaN
13,Taiwan,98.700000,98.530000,98.220000,97.520000,97.430000,97.890000,98.140000,98.250000,98.270000,...,107.000000,107.270000,107.370000,107.520000,107.800000,107.910000,107.980000,108.380000,108.500000,108.59000
14,Thailand,100.130000,100.050000,99.190000,97.170000,97.180000,98.700000,99.360000,99.650000,99.540000,...,107.220000,107.250000,108.160000,108.840000,108.500000,108.710000,108.790000,108.680000,108.610000,108.47000
15,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.892800,103.020902,...,115.327132,115.058881,115.142989,115.196991,115.387411,115.935848,115.940000,116.265451,116.652848,116.80158
16,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,107.044308,106.982859,106.405605,105.742547,105.073176,105.468773,106.480709,106.714967,107.029287,NaN

In [ ]:
df = df.melt(id_vars="Region", var_name="Date", value_name="Value")

                     Region     Date      Value
0                    Brunei  2020-01   99.99463
1                  Cambodia  2020-01  180.79900
2                     China  2020-01  105.40000
3     Hong Kong SAR (China)  2020-01   98.50000
4                     India  2020-01  150.20000
...                     ...      ...        ...
998               Sri Lanka  2024-11        NaN
999                  Taiwan  2024-11  108.59000
1000               Thailand  2024-11  108.47000
1001                Vietnam  2024-11  116.80158
1002               Mongolia  2024-11        NaN

[1003 rows x 3 columns]

In [223]:
from pandasql import sqldf
df2 = sqldf('select * from df where Region not in ("Cambodia", "China", "Hong Kong SAR (China)", "Malaysia", "Vietnam", "Thailand")')
df3 = sqldf('select * from df where Region in ("Cambodia", "China", "Hong Kong SAR (China)", "Malaysia", "Vietnam", "Thailand")')

In [11]:
import pandas as pd 

df = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\download zip\BIS Liquidity data.xlsx")
# df = df.iloc[:,:12]
df.head()

,FREQ,CURR_DENOM,BORROWERS_CTY,BORROWERS_SECTOR,LENDERS_SECTOR,L_POS_TYPE,L_INSTR,UNIT_MEASURE,TITLE,UNIT_MULT,DECIMALS,COLLECTION,AVAILABILITY,TIME_PERIOD,OBS_VALUE,OBS_STATUS,OBS_PRE_BREAK,OBS_CONF
0,Q,TO1,5J,A,B,I,A,771,International claims on all sectors (worldwide),0,2,NaN,A,2014-Q2,1.350,A,NaN,F
1,Q,TO1,5J,A,B,I,A,771,International claims on all sectors (worldwide),0,2,NaN,A,2014-Q3,4.734,A,NaN,F
2,Q,TO1,5J,A,B,I,A,771,International claims on all sectors (worldwide),0,2,NaN,A,2014-Q4,4.158,A,NaN,F
3,Q,TO1,5J,A,B,I,A,771,International claims on all sectors (worldwide),0,2,NaN,A,2015-Q1,5.497,A,NaN,F
4,Q,TO1,5J,A,B,I,A,771,International claims on all sectors (worldwide),0,2,NaN,A,2015-Q2,0.994,A,NaN,F

In [2]:
import pandas as pd
df = pd.read_excel(
            r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\download zip\VIX_History.xlsx",
            sheet_name=1,
        )
df["Date"] = df["Month"].astype(str) + "-" + df["Year"].astype(str)
df["Date"] = pd.to_datetime(df["Date"]).dt.to_period('M')
df

C:\Users\AhmadAizudeen\AppData\Local\Temp\ipykernel_31184\1074631392.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])

     Month  Year  avg(OPEN)  avg(HIGH)   avg(LOW)  avg(CLOSE)       Date
0        2  2025  19.570000  19.765000  17.220000   17.915000 2025-02-01
1        1  2025  17.127273  18.019091  16.234545   16.763636 2025-01-01
2       12  2024  15.608571  17.065238  14.678095   15.866190 2024-12-01
3       11  2024  16.367619  17.031429  15.585238   16.015238 2024-11-01
4       10  2024  19.902174  20.828261  19.191304   19.960870 2024-10-01
..     ...   ...        ...        ...        ...         ...        ...
417      5  1990  18.097727  18.097727  18.097727   18.097727 1990-05-01
418      4  1990  21.403500  21.403500  21.403500   21.403500 1990-04-01
419      3  1990  20.062273  20.062273  20.062273   20.062273 1990-03-01
420      2  1990  23.262632  23.262632  23.262632   23.262632 1990-02-01
421      1  1990  23.347273  23.347273  23.347273   23.347273 1990-01-01

[422 rows x 7 columns]

In [7]:
from datetime import date
today = date.today()
past_yr = str(int(str(today)[:4])-11) + '-01-01'
print(today,past_yr)

2025-02-05 2014-01-01

In [5]:
str(today)[4:]

'-02-05'