In [2]:
import requests as r 
import pandas as pd 
from bs4 import BeautifulSoup as bs

In [3]:
url = 'https://www.federalreserve.gov/newsevents/pressreleases/2024-press-fomc.htm'
response = r.get(url)

if response.status_code == 200:
    print("Request is successful!")

Request is successful!

In [6]:
soup = bs(response.content, 'html.parser')
soup

# response

<!DOCTYPE html>

<html class="no-js" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0 maximum-scale=1.6, user-scalable=1" name="viewport"/>
<meta content="The Federal Reserve Board of Governors in Washington DC." name="description">
<meta content="Board of Governors of the Federal Reserve System" property="og:site_name">
<meta content="article" property="og:type">
<meta content="2024 FOMC Press Releases" property="og:title"/>
<meta content="https://www.federalreserve.gov/images/social-media/social-default-image-opengraph.jpg" property="og:image"/>
<meta content="Board of Governors of the Federal Reserve System" property="og:image:alt"/>
<meta content="The Federal Reserve Board of Governors in Washington DC." property="og:description"/>
<meta content="https://www.federalreserve.gov/newsevents/pressreleases/2024-press-fomc.htm" property="og:url"/>
<meta content="summary" name="twitter:card"/>
<meta content="2024 FOMC Press Releases" name="twitter:title"/>
<meta content="https://www.federalreserve.gov/images/social-media/social-default-image-twitter.jpg" name="twitter:image"/>
<meta content="Board of Governors of the Federal Reserve System" name="twitter:image:alt"/>
<meta content="The Federal Reserve Board of Governors in Washington DC." name="twitter:description"/>
<title>Federal Reserve Board - 2024 FOMC Press Releases</title>
<link href="/css/bootstrap.css" rel="stylesheet" type="text/css"/>
<link href="/css/bluesteel-theme.css" rel="stylesheet" type="text/css"/>
<script src="/js/modernizr-latest.js" type="text/javascript"></script>
<script src="/js/grunticon.loader.js"></script>
<script>
            grunticon(["/css/icons.data.svg.css", "/css/icons.data.png.css", "/css/icons.fallback.css"]);
        </script>
<noscript>
<link href="/css/icons.fallback.css" rel="stylesheet"/>
</noscript>
<script src="/js/angular.min.js" type="text/javascript"></script>
<script src="/js/app.js" type="text/javascript"></script>
<!-- For Linear Gradients in IE9 or greater -->
<!--[if gte IE 9]>
            <style type="text/css">
              .gradient {
                 filter: none;
              }
            </style>
        <![endif]-->
</meta></meta></meta></head>
<body>
<a class="globalskip" href="#content">Skip to main content</a>
<nav class="nav-primary-mobile" id="nav-primary-mobile"></nav>
<div class="t1_nav navbar navbar-default navbar-fixed-top" role="navigation">
<div class="t1_container clearfix">
<a class="btn btn-default icon-FRB_logo-bw visible-xs-table-cell t1__btnlogo" href="/default.htm" id="logo" role="button"><span class="sr-only">Back to Home</span></a>
<a class="visible-xs-table-cell t1__banner" href="/default.htm" id="banner" role="button" title="Link to Home Page">Board of Governors of the Federal Reserve System</a>
<ul class="nav navbar-nav visible-md visible-lg t1_toplinks">
<li class="navbar-text navbar-text__social">
<span class="navbar-link" tabindex="0">Stay Connected</span>
<ul class="nav navbar-nav t1_social social_nine">
<li class="social__item">
<a class="noIcon" data-icon="facebook" href="https://www.facebook.com/federalreserve">
<div class="icon-facebook-color icon icon__sm"></div>
<span class="sr-only">Federal Reserve Facebook Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="instagram" href="https://www.instagram.com/federalreserveboard/">
<div class="icon-instagram icon icon__sm"></div>
<span class="sr-only">Federal Reserve Instagram Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="youtube" href="https://www.youtube.com/federalreserve">
<div class="icon-youtube-color icon icon__sm"></div>
<span class="sr-only">Federal Reserve YouTube Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="flickr" href="https://www.flickr.com/photos/federalreserve/">
<div class="icon-flickr-color icon icon__sm"></div>
<span class="sr-only">Federal Reserve Flickr Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="linkedin" href="https://www.linkedin.com/company/federal-reserve-board">
<div class="icon-linkedin-color icon icon__sm"></div>
<span class="sr-only">Federal Reserve LinkedIn Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="threads" href="https://www.threads.net/@federalreserveboard">
<div class="icon-threads icon icon__sm"></div>
<span class="sr-only">Federal Reserve Threads Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="twitter" href="https://twitter.com/federalreserve">
<div class="icon-twitter-color icon icon__sm"></div>
<span class="sr-only">Federal Reserve Twitter Page</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="rss" href="/feeds/feeds.htm">
<div class="icon-rss-color icon icon__sm"></div>
<span class="sr-only">Subscribe to RSS</span></a>
</li>
<li class="social__item">
<a class="noIcon" data-icon="email" href="/subscribe.htm">
<div class="icon-email-color icon icon__sm"></div>
<span class="sr-only">Subscribe to Email</span></a>
</li>
</ul>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/recentpostings.htm">Recent Postings</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/newsevents/calendar.htm">Calendar</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/publications.htm">Publications</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/sitemap.htm">Site Map</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/azindex.htm">A-Z index</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/careers.htm">Careers</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/faqs.htm">FAQs</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/videos.htm">Videos</a>
</li>
<li class="navbar-text">
<a class="navbar-link" href="/aboutthefed/contact-us-topics.htm">Contact</a>
</li>
</ul>
<form action="//www.fedsearch.org/board_public/search" class="nav navbar-form hidden-xs nav__search" method="get" role="search">
<div class="form-group input-group input-group-sm">
<label class="sr-only" for="t1search">Search</label>
<input class="nav__input form-control" id="t1search" name="text" placeholder="Search" type="text"/>
<span class="input-group-btn">
<button class="nav__button btn btn-default" id="headerTopLinksSearchFormSubmit" name="Search" type="submit">
<span class="sr-only">Submit Search Button</span>
<span class="icon-magnifying-glass icon icon__xs icon--right"></span>
</button>
</span>
</div>
<div class="nav__advanced">
<a class="noIcon" href="//www.fedsearch.org/board_public/">Advanced</a>
</div>
</form>
<div class="btn-group visible-xs-table-cell visible-sm-table-cell t1__dropdown">
<span class="icon icon__md icon--right dropdown-toggle icon-options-nav" data-toggle="dropdown">
<span class="sr-only">Toggle Dropdown Menu</span>
</span>
</div>
</div>
</div>
<header class="jumbotron hidden-xs">
<a class="jumbotron__link" href="/default.htm" title="Link to Home Page">
<div class="container-fluid">
<h1 class="jumbotron__heading">Board of Governors of the Federal Reserve System
            </h1>
<p class="jumbotron__content">
<em>The Federal Reserve, the central bank of the United States, provides
          the nation with a safe, flexible, and stable monetary and financial
          system.</em>
</p>
</div>
</a>
</header>
<div class="t2__offcanvas visible-xs-block">
<div class="navbar-header">
<button class="offcanvas__toggle icon-offcanvas-nav" data-canvas="body" data-target="#offcanvasT2Menu" data-toggle="offcanvas" type="button">
<span class="sr-only">Main Menu Toggle Button</span>
</button>
<span class="navbar-brand offcanvas__title">Sections</span>
<button class="offcanvas__search icon-search-nav" data-target="#navbar-collapse" data-toggle="collapse" type="button">
<span class="sr-only">Search Toggle Button</span>
</button>
</div>
<div class="navbar-collapse collapse mobile-form" id="navbar-collapse">
<form action="//www.fedsearch.org/board_public/search" class="navbar-form" method="get" role="search">
<div class="form-group input-group mobileSearch">
<label class="sr-only" for="t2search">Search</label>
<input class="form-control" id="t2search" name="text" placeholder="Search" type="text"/>
<span class="input-group-btn">
<span class="sr-only">Search Submit Button</span>
<button class="btn btn-default" type="submit">Submit</button>
</span>
</div>
</form>
</div>
</div>
<nav class="nav-primary navbar hidden-xs nav-nine" id="nav-primary" role="navigation">
<ul class="nav navbar-nav" role="menubar">
<li class="dropdown nav-about dropdown--3Col" role="menuitem">
<a aria-haspopup="true" class="sr-only-focusable" href="/aboutthefed.htm" id="aboutMenu">About<br/>the Fed</a>
<ul aria-labelledby="aboutMenu" class="dropdown-menu sub-nav-group navmenu-nav" role="menu">
<li>
<div class="row">
<ul class="col-sm-4 list-unstyled">
<li>
<a class="sr-only-focusable" href="/aboutthefed/fedexplained/who-we-are.htm">Structure of the Federal Reserve System</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/the-fed-explained.htm">The Fed Explained</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/bios/board/default.htm">Board Members</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/advisorydefault.htm">Advisory Councils</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/federal-reserve-system.htm">Federal Reserve Banks</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/directors/about.htm">Federal Reserve Bank and Branch Directors</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/fract.htm">Federal Reserve Act</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/currency.htm">Currency</a>
</li>
</ul>
<ul class="col-sm-4 list-unstyled">
<li>
<a class="sr-only-focusable" href="/aboutthefed/boardmeetings/meetingdates.htm">Board Meetings</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/boardvotes.htm">Board Votes</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/diversityinclusion.htm">Diversity &amp; Inclusion</a>
</li>
<li>
<a class="sr-only-focusable" href="/careers.htm">Careers</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/procurement/about.htm">Do Business with the Board</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/k8.htm">Holidays Observed - K.8</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/ethics-values.htm">Ethics &amp; Values</a>
</li>
</ul>
<ul class="col-sm-4 list-unstyled">
<li>
<a class="sr-only-focusable" href="/aboutthefed/contact-us-topics.htm">Contact</a>
</li>
<li>
<a class="sr-only-focusable" href="/foia/about_foia.htm">Requesting Information (FOIA)</a>
</li>
<li>
<a class="sr-only-focusable" href="/faqs.htm">FAQs</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/educational-tools/default.htm">Economic Education</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/fed-financial-statements.htm">Fed Financial Statements</a>
</li>
<li>
<a class="sr-only-focusable" href="/aboutthefed/innovation.htm">Innovation</a>
</li>
</ul>
</div>
</li>
</ul>
</li>
<li class="dropdown nav-news dropdown--1Col" role="menuitem">
<a aria-haspopup="true" class="sr-only-focusable" href="/newsevents.htm" id="newsMenu">News<br/>&amp; Events</a>
<ul aria-labelledby="newsMenu" class="dropdown-menu sub-nav-group navmenu-nav" role="menu">
<li>
<a class="sr-only-focusable" href="/newsevents/pressreleases.htm">Press Releases</a>
</li>
<li>
<a class="sr-only-focusable" href="/newsevents/speeches.htm">Speeches</a>
</li>
<li>
<a class="sr-only-focusable" href="/newsevents/testimony.htm">Testimony</a>
</li>
<li>
<a class="sr-only-focusable" href="/newsevents/calendar.htm">Calendar</a>
</li>
<li>
<a class="sr-only-focusable" href="/videos.htm">Videos</a>
</li>
<li>
<a class="sr-only-focusable" href="/photogallery.htm">Photo Gallery</a>
</li>
<li>
<a class="sr-only-focusable" href="/conferences.htm">Conferences</a>
</li>
</ul>
</li>
<li class="dropdown nav-monetary dropdown--2Col" role="menuitem">
<a aria-haspopup="true" class="sr-only-focusable" href="/monetarypolicy.htm" id="monetaryMenu">Monetary<br/>Policy</a>
<ul aria-labelledby="monetaryMenu" class="dropdown-menu sub-nav-group navmenu-nav" role="menu">
<li>
<div class="row">
<ul class="col-sm-6 list-unstyled">
<li class="nav__header">
<p>
<strong>Federal Open Market Committee</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/fomc.htm">About the FOMC</a>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/fomccalendars.htm">Meeting calendars and information</a>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/fomc_historical.htm">Transcripts and other historical materials</a>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/fomc_projectionsfaqs.htm">FAQs</a>
</li>
<li class="nav__header">
<p>
<strong>Monetary Policy Principles and Practice</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/monetary-policy-principles-and-practice.htm">Notes</a>
</li>
</ul>
<ul class="col-sm-6 list-unstyled">
<li class="nav__header">
<p>
<strong>Policy Implementation</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/policy-normalization.htm">Policy Normalization</a>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/policytools.htm">Policy Tools</a>
</li>
<li class="nav__header">
<p>
<strong>Reports</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/publications/mpr_default.htm">Monetary Policy Report</a>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/publications/beige-book-default.htm">Beige Book</a>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/publications/balance-sheet-developments-report.htm">Federal Reserve Balance Sheet Developments</a>
</li>
<li class="nav__header">
<p>
<strong>Review of Monetary Policy Strategy, Tools, and Communications</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/monetarypolicy/review-of-monetary-policy-strategy-tools-and-communications.htm">Overview</a>
</li>
</ul>
</div>
</li>
</ul>
</li>
<li class="dropdown nav-supervision dropdown--fw" role="menuitem">
<a aria-haspopup="true" class="sr-only-focusable" href="/supervisionreg.htm" id="supervisionMenu">Supervision<br/>&amp; Regulation</a>
<ul aria-labelledby="supervisionMenu" class="dropdown-menu sub-nav-group navmenu-nav" role="menu">
<li>
<div class="row">
<ul class="col-sm-3 col-nav list-unstyled">
<li class="nav__header">
<p>
<strong>Institution Supervision</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/novel-activities-supervision-program.htm">Novel Activities Supervision Program</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/community-and-regional-financial-institutions.htm">Community &amp; Regional Financial Institutions</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/large-financial-institutions.htm">Large Financial Institutions</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/foreign-banking-organizations.htm">Foreign Banking Organizations</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/financial-market-utility-supervision.htm">Financial Market Utilities</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/consumer-compliance.htm">Consumer Compliance</a>
</li>
<li class="nav__header">
<p>
<strong>Reports</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/publications/supervision-and-regulation-report.htm">Federal Reserve Supervision and Regulation Report</a>
</li>
</ul>
<ul class="col-sm-3 list-unstyled col-nav">
<li class="nav__header">
<p>
<strong>Reporting Forms</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/apps/reportingforms">All Reporting Forms</a>
</li>
<li>
<a class="sr-only-focusable" href="/apps/reportingforms/recentupdates">Recent Updates</a>
</li>
<li>
<a class="sr-only-focusable" href="/apps/reportingforms/home/review">Information collections under review</a>
</li>
<li>
<a class="sr-only-focusable" href='/apps/ReportingForms/?reportTypesIdsJson=["1"]'>Financial Statements</a>
</li>
<li>
<a class="sr-only-focusable" href='/apps/ReportingForms/?reportTypesIdsJson=["2"]'>Applications/structure change</a>
</li>
<li>
<a class="sr-only-focusable" href='/apps/ReportingForms/?reportTypesIdsJson=["3"]'>Federal Financial Institutions Examination Council (FFIEC)</a>
</li>
<li>
<a class="sr-only-focusable" href='/apps/ReportingForms/?reportTypesIdsJson=["8"]'>Municipal &amp; Government Securities</a>
</li>
</ul>
<ul class="col-sm-3 list-unstyled col-nav">
<li class="nav__header">
<p>
<strong>Supervision &amp; Regulation Letters</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/srletters/srletters.htm">By Year</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/topics/topics.htm">By Topic</a>
</li>
<li class="nav__header">
<p>
<strong>Banking Applications &amp; Legal Developments</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/application-process.htm">Application Process</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/board-and-reserve-bank-actions.htm">Board &amp; Reserve Bank Action</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/legal-developments.htm">Enforcement Actions &amp; Legal Developments</a>
</li>
</ul>
<ul class="col-sm-3 list-unstyled col-nav">
<li class="nav__header">
<p>
<strong>Regulatory Resources</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/reglisting.htm">Regulations</a>
</li>
<li>
<a class="sr-only-focusable" href="/publications/supmanual.htm">Manuals</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/basel/basel-default.htm">Basel Regulatory Framework</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/volcker-rule.htm">Volcker Rule</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/training-and-assistance-landing.htm">Education, Training, and Assistance</a>
</li>
</ul>
<ul class="col-sm-3 list-unstyled col-nav">
<li class="nav__header">
<p>
<strong>Banking &amp; Data Structure</strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/apps/reportforms/insider.aspx">Beneficial Ownership reports</a>
</li>
<li>
<a class="sr-only-focusable" href="/releases/lbr/">Large Commercial Banks</a>
</li>
<li>
<a class="sr-only-focusable" href="/releases/iba/">U.S. Offices of Foreign Entities</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/fhc.htm">Financial Holding Companies</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/isb-default.htm">Interstate Branching</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/suds.htm">Securities Underwriting &amp; Dealing Subsidiaries</a>
</li>
<li>
<a class="sr-only-focusable" href="/supervisionreg/minority-depository-institutions.htm">Minority Depository Institutions</a>
</li>
</ul>
</div>
</li>
</ul>
</li>
<li class="dropdown nav-stability dropdown--2Col" role="menuitem">
<a aria-haspopup="true" class="sr-only-focusable" href="/financial-stability.htm" id="stabilityMenu">Financial<br/>Stability</a>
<ul aria-labelledby="stabilityMenu" class="dropdown-menu sub-nav-group navmenu-nav" role="menu">
<div class="row">
<ul class="col-sm-6 list-unstyled">
<li class="nav__header">
<p>
<strong>Financial Stability Assessments </strong>
</p>
</li>
<li>
<a class="sr-only-focusable" href="/financial-stability/what-is-financial-stability.htm">About Financial Stability</a>
</li>
<li>
<a class="sr-only-focusable" href="/financial-stability/types-of-financial-system-vulnerabilities-and-risks.htm">Types of Financial System Vulnerabilities &amp; Risks</a>
</li>
<li>

In [29]:
div = soup.find_all(class_ = 'col-xs-12 col-sm-8 col-md-8')
div[0]

<div class="col-xs-12 col-sm-8 col-md-8">
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>11/7/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20241107a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>9/18/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240918a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>9/18/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240918b.htm"><em>Federal Reserve Board and Federal Open Market Committee release economic projections from the September 17-18 FOMC meeting</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>7/31/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240731a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>6/12/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240612a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>6/12/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240612b.htm"><em>Federal Reserve Board and Federal Open Market Committee release economic projections from the June 11-12 FOMC meeting</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>5/1/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240501a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>3/20/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240320a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>3/20/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240320b.htm"><em>Federal Reserve Board and Federal Open Market Committee release economic projections from the March 19-20 FOMC meeting</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>1/31/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240131a.htm"><em>Federal Reserve issues FOMC statement</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>1/31/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240131b.htm"><em>Federal Open Market Committee reaffirms its "Statement on Longer-Run Goals and Monetary Policy Strategy"</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-2 eventlist__time">
<time>1/31/2024</time>
</div>
<div class="col-xs-9 col-md-10 eventlist__event">
<p><a href="/newsevents/pressreleases/monetary20240131c.htm"><em>Federal Open Market Committee announces updates that further enhance its policy on investment and trading</em></a></p>
<p class="eventlist__press"><em><strong>Monetary Policy</strong></em></p>
</div>
</div>
</div>

In [26]:
soup2 = bs(div[0], 'html.parser')
soup2

TypeError: 'NoneType' object is not callable

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vladtasca/fomc-meeting-statements-and-minutes", force_download=True)

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/vladtasca/fomc-meeting-statements-and-minutes?dataset_version_number=45...

100%|██████████| 2.91M/2.91M [00:01<00:00, 1.71MB/s]

Extracting files...
Path to dataset files: C:\Users\AhmadAizudeen\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45

In [3]:
import pandas as pd

df = pd.read_csv(r'C:\Users\AhmadAizudeen\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45\communications.csv')
df.head()

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...
2,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
3,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
4,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...

In [15]:
from pandasql import sqldf as sd

sd('select * from df order by "Release Date" desc')

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...
2,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
3,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...
4,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
...,...,...,...,...
436,2001-09-17,None,Minute,Minutes of the Federal Open Market Committee\n...
437,2001-09-13,None,Minute,Minutes of the Federal Open Market Committee\n...
438,2001-04-18,None,Minute,Minutes of the Federal Open Market Committee\n...
439,2001-04-11,None,Minute,Minutes of the Federal Open Market Committee\n...
440,2001-01-03,None,Minute,Minutes of the Federal Open Market Committee\n...

In [25]:
df2 = sd('select * from df where Type = "Statement"')
df2.head()

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
2,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
3,2024-07-31,2024-07-31,Statement,Recent indicators suggest that economic activi...
4,2024-06-12,2024-06-12,Statement,Recent indicators suggest that economic activi...

In [29]:
df.tail()

,Date,Release Date,Type,Text
436,2000-05-16,2000-05-16,Statement,The Federal Open Market Committee voted today ...
437,2000-03-21,2000-05-18,Minute,Minutes of the Federal Open Market Committee\n...
438,2000-03-21,2000-03-21,Statement,The Federal Open Market Committee voted today ...
439,2000-02-02,2000-03-23,Minute,Minutes of the Federal Open Market Committee\n...
440,2000-02-02,2000-02-02,Statement,The Federal Open Market Committee voted today ...

In [30]:
sd('select count(Text) from df where Type = "Minute"')

   count(Text)
0          229

In [2]:
from textblob import TextBlob

def score_sentence_with_textblob(sentence):
    blob = TextBlob(sentence)
    polarity = blob.sentiment.polarity
    return polarity

# Example usage:
sentence = "fuck"
print(score_sentence_with_textblob(sentence))

-0.4

In [3]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

sentence = "It was a good day but with some bad moments."
tokens = word_tokenize(sentence)
print(tokens)  # Output: ['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\AhmadAizudeen\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

In [104]:
import pandas as pd 

df = pd.read_excel('Aruoba_Drechsel_Data.xlsx', sheet_name='Sentiments overview')
df = df.rename(columns={'Includes (because synonym or closely related)':'Includes', 'Excludes (these are separate sentiments unless they appear infrequently)':'Excludes'})
df['Includes2'] = df.apply(
    lambda row: row['Sentiment label'] + ', ' + row['Includes'] if pd.notna(row['Includes']) else row['Sentiment label'],
    axis=1
)
df.head()

,Sentiment label,Includes,Excludes,Includes2
0,borrowing,borrowers,NaN,"borrowing, borrowers"
1,brazil,brazilian,NaN,"brazil, brazilian"
2,banks,"bank, banking, bankers",district banks,"banks, bank, banking, bankers"
3,canada,canadian,NaN,"canada, canadian"
4,credit,NaN,"credit standards, credit quality",credit

In [102]:
df2 = df[['Includes2', 'Excludes']].map(lambda x: None if str(x).split(', ')[0] == 'nan' else str(x).split(', '))
df2.head()

                         Includes2                            Excludes
0           [borrowing, borrowers]                                None
1              [brazil, brazilian]                                None
2  [banks, bank, banking, bankers]                    [district banks]
3               [canada, canadian]                                None
4                         [credit]  [credit standards, credit quality]

In [140]:
def func():
df2['Includes3'] = df2['Includes2'].map(lambda x : x)

                           Includes2                            Excludes
0             [borrowing, borrowers]                                None
1                [brazil, brazilian]                                None
2    [banks, bank, banking, bankers]                    [district banks]
3                 [canada, canadian]                                None
4                           [credit]  [credit standards, credit quality]
..                               ...                                 ...
291                    [contractors]                                None
292              [corporate profits]                                None
293            [insurance companies]                                None
294                 [wage pressures]                                None
295            [market expectations]                                None

[296 rows x 2 columns]

In [127]:
from nltk.tokenize import RegexpTokenizer
from pandasql import sqldf as sd

fomc = pd.read_csv(r'C:\Users\AhmadAizudeen\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45\communications.csv')
fomc = sd('select * from fomc where Type = "Minute"')
tokenizer = RegexpTokenizer(r'\w+')

fomc['tokenized text'] = fomc['Text'].map(lambda x : tokenizer.tokenize(x.lower()))
fomc.head()

,Date,Release Date,Type,Text,tokenized text
0,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
1,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
2,2024-07-31,2024-08-21,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
3,2024-06-12,2024-07-03,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
4,2024-05-01,2024-05-22,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."

In [133]:
eco_ind = pd.read_excel('Aruoba_Drechsel_Data.xlsx', sheet_name='Sentiments by meeting', index_col=0)
eco_ind.head()

,borrowing,brazil,banks,canada,credit,china,consumption,construction,currencies,deposits,...,russia,workers,economic expansion,economic data,canadian dollar,contractors,corporate profits,insurance companies,wage pressures,market expectations
FOMC meeting (scheduled),,,,,,,,,,,,,,,,,,,,,
1982_10_05,-2.248049,-0.397627,-2.069843,-0.532678,0.339695,0.419825,-1.400883,-1.693100,1.100398,-1.343805,...,0.365198,-1.665561,0.260666,-0.870816,-0.087391,0.219267,-1.865366,0.262187,0.664378,0.459712
1982_11_16,-3.872575,-1.991724,-1.762177,-1.310815,0.287549,0.419825,-1.385852,-1.069244,-0.347396,-1.162794,...,0.365198,-2.961253,0.260666,0.321653,-0.083493,0.219267,-5.187434,-0.690550,0.664378,0.459712
1982_12_21,-2.330907,1.003767,-1.663421,-0.700483,-0.796532,0.419825,0.148721,-1.149710,-1.565683,-1.759771,...,0.365198,0.484308,0.260666,0.321653,1.810921,-0.254227,-2.161714,0.262187,0.664378,0.459712
1983_02_09,-0.358473,0.507433,0.854820,0.282557,0.806648,0.019820,0.568375,0.453294,-0.025795,-2.211075,...,0.365198,-3.789039,-1.923855,0.321653,0.423312,0.219267,-1.764862,1.179239,0.664378,-3.268755
1983_03_29,-0.421778,-0.301260,0.181621,-0.708089,0.814349,0.419825,1.728527,1.667024,0.543804,0.203953,...,0.365198,-0.057465,0.260666,0.321653,0.423312,-1.684726,-1.664541,-1.486045,0.664378,0.459712

In [138]:
len(list(eco_ind.columns))

296