In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vladtasca/fomc-meeting-statements-and-minutes", force_download=True)

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/vladtasca/fomc-meeting-statements-and-minutes?dataset_version_number=45...

100%|██████████| 2.91M/2.91M [00:01<00:00, 1.92MB/s]

Extracting files...
Path to dataset files: C:\Users\Admin\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45

In [7]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Admin\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45\communications.csv')
df.head()

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...
2,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
3,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
4,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...

In [8]:
from pandasql import sqldf as sd

sd('select * from df order by "Release Date" desc')

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...
2,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
3,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...
4,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
...,...,...,...,...
436,2001-09-17,None,Minute,Minutes of the Federal Open Market Committee\n...
437,2001-09-13,None,Minute,Minutes of the Federal Open Market Committee\n...
438,2001-04-18,None,Minute,Minutes of the Federal Open Market Committee\n...
439,2001-04-11,None,Minute,Minutes of the Federal Open Market Committee\n...
440,2001-01-03,None,Minute,Minutes of the Federal Open Market Committee\n...

In [9]:
df2 = sd('select * from df where Type = "Statement"')
df2.head()

,Date,Release Date,Type,Text
0,2024-12-18,2024-12-18,Statement,Recent indicators suggest that economic activi...
1,2024-11-07,2024-11-07,Statement,Recent indicators suggest that economic activi...
2,2024-09-18,2024-09-18,Statement,Recent indicators suggest that economic activi...
3,2024-07-31,2024-07-31,Statement,Recent indicators suggest that economic activi...
4,2024-06-12,2024-06-12,Statement,Recent indicators suggest that economic activi...

In [10]:
df.tail()

,Date,Release Date,Type,Text
436,2000-05-16,2000-05-16,Statement,The Federal Open Market Committee voted today ...
437,2000-03-21,2000-05-18,Minute,Minutes of the Federal Open Market Committee\n...
438,2000-03-21,2000-03-21,Statement,The Federal Open Market Committee voted today ...
439,2000-02-02,2000-03-23,Minute,Minutes of the Federal Open Market Committee\n...
440,2000-02-02,2000-02-02,Statement,The Federal Open Market Committee voted today ...

In [11]:
sd('select count(Text) from df where Type = "Minute"')

   count(Text)
0          229

In [12]:
from textblob import TextBlob

def score_sentence_with_textblob(sentence):
    blob = TextBlob(sentence)
    polarity = blob.sentiment.polarity
    return polarity

# Example usage:
sentence = "fuck"
print(score_sentence_with_textblob(sentence))

-0.4

In [15]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

sentence = "It was a good day but with some bad moments."
# tokens = word_tokenize(sentence)
# print(tokens)  # Output: ['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [17]:
nltk.download('punkt_tab')
tokens = word_tokenize(sentence)
print(tokens)  # Output: ['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...

['It', 'was', 'a', 'good', 'day', 'but', 'with', 'some', 'bad', 'moments', '.']

[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

In [104]:
import pandas as pd 

df = pd.read_excel('Aruoba_Drechsel_Data.xlsx', sheet_name='Sentiments overview')
df = df.rename(columns={'Includes (because synonym or closely related)':'Includes', 'Excludes (these are separate sentiments unless they appear infrequently)':'Excludes'})
df['Includes2'] = df.apply(
    lambda row: row['Sentiment label'] + ', ' + row['Includes'] if pd.notna(row['Includes']) else row['Sentiment label'],
    axis=1
)
df.head()

,Sentiment label,Includes,Excludes,Includes2
0,borrowing,borrowers,NaN,"borrowing, borrowers"
1,brazil,brazilian,NaN,"brazil, brazilian"
2,banks,"bank, banking, bankers",district banks,"banks, bank, banking, bankers"
3,canada,canadian,NaN,"canada, canadian"
4,credit,NaN,"credit standards, credit quality",credit

In [102]:
df2 = df[['Includes2', 'Excludes']].map(lambda x: None if str(x).split(', ')[0] == 'nan' else str(x).split(', '))
df2.head()

                         Includes2                            Excludes
0           [borrowing, borrowers]                                None
1              [brazil, brazilian]                                None
2  [banks, bank, banking, bankers]                    [district banks]
3               [canada, canadian]                                None
4                         [credit]  [credit standards, credit quality]

In [140]:
def func():
df2['Includes3'] = df2['Includes2'].map(lambda x : x)

                           Includes2                            Excludes
0             [borrowing, borrowers]                                None
1                [brazil, brazilian]                                None
2    [banks, bank, banking, bankers]                    [district banks]
3                 [canada, canadian]                                None
4                           [credit]  [credit standards, credit quality]
..                               ...                                 ...
291                    [contractors]                                None
292              [corporate profits]                                None
293            [insurance companies]                                None
294                 [wage pressures]                                None
295            [market expectations]                                None

[296 rows x 2 columns]

In [127]:
from nltk.tokenize import RegexpTokenizer
from pandasql import sqldf as sd

fomc = pd.read_csv(r'C:\Users\AhmadAizudeen\.cache\kagglehub\datasets\vladtasca\fomc-meeting-statements-and-minutes\versions\45\communications.csv')
fomc = sd('select * from fomc where Type = "Minute"')
tokenizer = RegexpTokenizer(r'\w+')

fomc['tokenized text'] = fomc['Text'].map(lambda x : tokenizer.tokenize(x.lower()))
fomc.head()

,Date,Release Date,Type,Text,tokenized text
0,2024-11-07,2024-11-26,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
1,2024-09-18,2024-10-09,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
2,2024-07-31,2024-08-21,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
3,2024-06-12,2024-07-03,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."
4,2024-05-01,2024-05-22,Minute,Minutes of the Federal Open Market Committee\n...,"[minutes, of, the, federal, open, market, comm..."

In [133]:
eco_ind = pd.read_excel('Aruoba_Drechsel_Data.xlsx', sheet_name='Sentiments by meeting', index_col=0)
eco_ind.head()

,borrowing,brazil,banks,canada,credit,china,consumption,construction,currencies,deposits,...,russia,workers,economic expansion,economic data,canadian dollar,contractors,corporate profits,insurance companies,wage pressures,market expectations
FOMC meeting (scheduled),,,,,,,,,,,,,,,,,,,,,
1982_10_05,-2.248049,-0.397627,-2.069843,-0.532678,0.339695,0.419825,-1.400883,-1.693100,1.100398,-1.343805,...,0.365198,-1.665561,0.260666,-0.870816,-0.087391,0.219267,-1.865366,0.262187,0.664378,0.459712
1982_11_16,-3.872575,-1.991724,-1.762177,-1.310815,0.287549,0.419825,-1.385852,-1.069244,-0.347396,-1.162794,...,0.365198,-2.961253,0.260666,0.321653,-0.083493,0.219267,-5.187434,-0.690550,0.664378,0.459712
1982_12_21,-2.330907,1.003767,-1.663421,-0.700483,-0.796532,0.419825,0.148721,-1.149710,-1.565683,-1.759771,...,0.365198,0.484308,0.260666,0.321653,1.810921,-0.254227,-2.161714,0.262187,0.664378,0.459712
1983_02_09,-0.358473,0.507433,0.854820,0.282557,0.806648,0.019820,0.568375,0.453294,-0.025795,-2.211075,...,0.365198,-3.789039,-1.923855,0.321653,0.423312,0.219267,-1.764862,1.179239,0.664378,-3.268755
1983_03_29,-0.421778,-0.301260,0.181621,-0.708089,0.814349,0.419825,1.728527,1.667024,0.543804,0.203953,...,0.365198,-0.057465,0.260666,0.321653,0.423312,-1.684726,-1.664541,-1.486045,0.664378,0.459712

In [138]:
len(list(eco_ind.columns))

296

In [17]:
def calc(P=1450, r=0.053, n=30, inc = 114):
    fv = 0
    for x in range(n):
        if fv > 0:
            ttl_month = 12
            P = P + inc
            fv2 = P*(((1+r/12)**ttl_month)-1)/(r/12)
            fv = fv + fv2
        elif fv == 0:
            ttl_month = 12
            fv2 = P*(((1+r/12)**ttl_month)-1)/(r/12)
            fv = fv + fv2
    return fv

calc()

17828.95999276154

In [14]:
total, interest, n, increment = 0, 0, 2, 114
for x in range(n):
    fv = calc()
    total = total + fv
    # interest = interest + y
print(total)

35657.91998552308

In [102]:
import pandas as pd

df = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\SEACEN CFM Data.xlsx",sheet_name=5)
df

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\AhmadAizudeen\\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\\Roger and Aizudeen\\SEACEN CFM Data.xlsx'

In [85]:
df['Date'] = df['Month'].astype(str) + '/' + df['Year'].astype(str)
df = df.rename(columns={'avg(CLOSE)': 'CLOSE'})
df

     Month  Year  avg(OPEN)  avg(HIGH)   avg(LOW)      CLOSE     Date
0        1  2025  17.127273  18.019091  16.234545  16.763636   1/2025
1       12  2024  15.608571  17.065238  14.678095  15.866190  12/2024
2       11  2024  16.367619  17.031429  15.585238  16.015238  11/2024
3       10  2024  19.902174  20.828261  19.191304  19.960870  10/2024
4        9  2024  17.827143  18.811905  16.804762  17.663333   9/2024
..     ...   ...        ...        ...        ...        ...      ...
416      5  1990  18.097727  18.097727  18.097727  18.097727   5/1990
417      4  1990  21.403500  21.403500  21.403500  21.403500   4/1990
418      3  1990  20.062273  20.062273  20.062273  20.062273   3/1990
419      2  1990  23.262632  23.262632  23.262632  23.262632   2/1990
420      1  1990  23.347273  23.347273  23.347273  23.347273   1/1990

[421 rows x 7 columns]

In [95]:
df[['Date', 'CLOSE']].iloc[::-1][360:]

       Date      CLOSE
60   1/2020  13.940952
59   2/2020  19.628947
58   3/2020  57.736818
57   4/2020  41.453810
56   5/2020  30.897000
..      ...        ...
4    9/2024  17.663333
3   10/2024  19.960870
2   11/2024  16.015238
1   12/2024  15.866190
0    1/2025  16.763636

[61 rows x 2 columns]

In [51]:
df[['Month', 'Year']] = df[['Month', 'Year']].astype(str).dtypes

C:\Users\AhmadAizudeen\AppData\Local\Temp\ipykernel_7772\278127432.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df[['Month', 'Year']] = df[['Month', 'Year']].astype(str).dtypes

In [61]:
df['Date'] = '/'.join([df['Month'],df['Year']])
df

TypeError: sequence item 0: expected str instance, Series found

In [60]:
'/'.join(['1','2'])

'1/2'