In [5]:
import pandas as pd
from datetime import datetime
import os

df_init = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\data science project\cfm-nlp\cfm-nlp\Automation.xlsx", sheet_name='IIP edit')

path_dict = dict()
list_1 = ['IMF IIP Annual.xlsx', 'IMF IIP Quarterly.xlsx']
# directory_path= r'C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data'
directory_path= r'C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data'
for filename in os.listdir(directory_path):
    if filename in ['01 Emerging Market', '02 G7 Countries']:
        continue
    file_path = os.path.join(directory_path, filename)
    list_temp = []
    for filename2 in os.listdir(file_path):
        if any(word in str(filename2) for word in list_1):            
            list_temp.append(filename2)
            path_dict[filename] = list_temp
        else:
            continue

df_path = []
for k, v in path_dict.items():
    df_path.append(os.path.join(directory_path, k, v[1]))
    # print(v[1]) ## to check the file name

df_all_annual = pd.DataFrame()
for x, y in enumerate(df_path):
    df = pd.read_excel(y)
    df = df[df[df.columns[0]].isin(df_init['desc'])]
    df_all_annual = pd.concat([df_all_annual, df]) 

df_all_annual.rename(columns={df_all_annual.columns[0]: 'Type'}, inplace=True)

df_all_annual_2 = df_all_annual[df_all_annual.columns[:4].to_list() + [dt for dt in df_all_annual.columns[4:].sort_values(ascending=True).to_list() if dt >= datetime(2019, 1, 1)]]

df_init_tw = pd.read_excel(r"C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\cfm-nlp\Automation.xlsx", sheet_name='Taiwan IIP')
df_tw = pd.read_excel(r"C:\Users\Admin\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data\Chinese Taipei (Taiwan) (TW)\TW CB IIP Annual.xlsx")
df_tw.rename(columns={df_tw.columns[0]: 'Type'}, inplace=True)
df_tw = df_tw[df_tw['Type'].isin(df_init_tw['desc'])]

for x, y in enumerate(df_tw['Type'].to_list()):
    df_tw.iat[x,0] = list(df_init_tw[(df_init_tw['desc'] == y)]['desc2'])[0]

selected_columns = [col for col in df_tw.columns[4:] if pd.to_datetime(col) >= datetime(2019, 1, 1)]
final_columns = list(df_tw.columns[:4]) + selected_columns
df_tw = df_tw[final_columns]

####baru
tw_col1 = df_all_annual_2.columns[4:][~df_all_annual_2.columns[4:].isin(df_tw.columns[4:])]
tw_col2 = {x.year:x for x in df_tw.columns[4:]}
df_tw2 = df_tw.copy()

for x in tw_col1:
    year = x.year
    if year in list(tw_col2.keys()):
        df_tw2[x] = df_tw2[tw_col2[year]]
    else:
        df_tw2[x] = None
####baru

df_all_annual_2 = pd.concat([df_all_annual_2, df_tw2], axis=0)

seacen_country = ['Papua New Guinea', 'Vietnam', 'Nepal', 'India', 'Indonesia', 'Laos', 'Sri Lanka', 'Hong Kong SAR (China)', 'Philippines', 'Taiwan', 'Malaysia', 'Mongolia', 'China', 'Cambodia', 'Thailand', 'Singapore', 'South Korea', 'Brunei', 'Myanmar']

for x in df_all_annual_2['Type'].values:
    var1 = list(set(df_all_annual_2[(df_all_annual_2['Type'] == x)]['Region'].values).symmetric_difference(set(seacen_country)))
    if len(var1) > 0:
        for y in var1:
            df_temp1 = pd.DataFrame({"Type": [x], "Region": [y]})
            df_all_annual_2 = pd.concat([df_all_annual_2, df_temp1], axis=0)
    else:
        continue

df_all_annual_2.sort_values(by=['Type', 'Region'], inplace=True)
df_all_annual_2.reset_index(drop=True, inplace=True)

init_dict = df_init.to_dict()
df_dict = dict()
for x in init_dict['desc'].values():
    df_temp = df_all_annual_2[(df_all_annual_2[df_all_annual_2.columns[0]] == x)].reset_index(drop=True)
    df_dict[x] = df_temp

var1 = {x*3:x for x in range(1,5)}
var2 = [f'{var1[x.month]}Q{x.year}' for x in df_all_annual_2.columns[4:].to_list()]
var3 = [x for x in var2 if x[:2] in ['2Q', '4Q']]
var4 = {'2Q':'1H', '4Q': '2H'}
var5 = [f'{var4[x[:2]]}{x[2:]}' for x in var3]

df_temp_col_1 = df_all_annual_2.rename(columns={k:v for k, v in zip(df_all_annual_2.columns[4:].to_list(), var2)})
df_temp_col_1 = df_temp_col_1[[*df_temp_col_1.columns[:4], *var3]]
df_temp_col_1.rename(columns={k:v for k,v in zip(var3, var5)}, inplace= True)
df_temp_col_1[df_temp_col_1.columns[4:]] = df_temp_col_1[df_temp_col_1.columns[4:]]/1000

df_temp_col_1.drop(columns=['Last Update Time', 'Unit'], inplace=True)

calc_dict = {'Asia-Pacific': seacen_country,
            'Asian Advance Economies': ['Hong Kong SAR (China)', 'South Korea', 'Singapore', 'Taiwan'],
            'ASEAN5 Economies': ['Indonesia', 'Malaysia', 'Philippines', 'Thailand', 'Vietnam'],
            'Asian EDMEs': ['Brunei', 'Cambodia', 'Laos', 'Mongolia', 'Nepal', 'Sri Lanka', 'Papua New Guinea', 'Myanmar'],
            'China': ['China'],
            'India': ['India'],
            }

C:\Users\Admin\AppData\Local\Temp\ipykernel_13864\2783400462.py:63: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all_annual_2 = pd.concat([df_all_annual_2, df_tw2], axis=0)

In [20]:
###################### this is for equity ######################

asset_row = df_init.iloc[[0,4,5,6,8,9,10,11,12,13,14]]['desc'].to_list()
asset_row2 = df_init.iloc[[0,4,5,6,8,9,10,11,12,13,14]]['short_title'].to_list()
sum_rows = df_init[(df_init['short_title'].isin([asset_row2[4], asset_row2[7], asset_row2[9]]))]['desc'].to_list()
order = ['Direct Investment','Portfolio Equity','Portfolio Debt','Financial Derivatives','Currency & Deposits','Loans','Trade Credit & Advances','Other Investments','Reserve Assets',]
df_by_region_main = pd.DataFrame(columns=df_temp_col_1.columns)

for x,y in calc_dict.items():
    # print(x,y)
    df_by_region_temp = df_temp_col_1[(df_temp_col_1['Region'].isin(y)) & (df_temp_col_1['Type'].isin(asset_row))]
    df_by_region_temp = df_by_region_temp.groupby(['Type']).sum()
    df_by_region_temp.loc[str(x) + ' Total'] = df_by_region_temp.sum()
    df_by_region_temp.loc['Other Investments'] = df_by_region_temp.loc[sum_rows].sum()
    df_by_region_temp.reset_index(inplace = True)
    df_by_region_temp = df_by_region_temp[(~df_by_region_temp['Type'].isin(sum_rows))] #####  the symbol of '~' use similar like notin, the oposite of isin. this is build in python operator
    df_by_region_temp['Type'] = df_by_region_temp['Type'].replace(asset_row, asset_row2)
    df_by_region_temp = df_by_region_temp.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(order)}))
    df_by_region_temp['Region'] = x

    df_by_region_main = pd.concat([df_by_region_main, df_by_region_temp], axis = 0)  


df_by_region_main.reset_index(inplace = True, drop=True)
df_by_region_main.insert(loc=0, column='Group', value='Assets')

###################### this is for equity ######################
# 0,4,5,6,8,9,10,11,12,13,14

# df_by_region_main[(df_by_region_main['Type'] == 'Other Investments')]
df_by_region_main['Type'].unique()
# 4, 7, 9

C:\Users\Admin\AppData\Local\Temp\ipykernel_13864\2175195883.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_by_region_main = pd.concat([df_by_region_main, df_by_region_temp], axis = 0)

array(['Other Investments', 'FDI Assets', 'Financial Derivative Assets',
       'Official Reserve Assets', 'Currency and Deposits Assets',
       'Loans Assets', 'Trade Credits and Advances Assets',
       'Portfolio Debt Assets', 'Portfolio Equity Assets',
       'Asia-Pacific Total', 'Asian Advance Economies Total',
       'ASEAN5 Economies Total', 'Asian EDMEs Total', 'China Total',
       'India Total'], dtype=object)

In [14]:
df_init2 = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\data science project\cfm-nlp\cfm-nlp\Automation.xlsx", sheet_name='BoP edit')
df_init2[(df_init2['short_title'] == 'Other Investments')]

Empty DataFrame
Columns: [group, short_title, desc]
Index: []

In [17]:
###################### this is for debt ######################

debt_row = df_init.iloc[[16,20,21,22,24,25,26,27,28,29,30]]['desc'].to_list()
debt_row2 = df_init.iloc[[16,20,21,22,24,25,26,27,28,29,30]]['short_title'].to_list()
sum_rows2 = df_init[(df_init['short_title'].isin(df_init.iloc[[24,27,29,30]]['short_title'].to_list()))]['desc'].to_list()
order2 = ['Direct Investment','Portfolio Equity','Portfolio Debt','Financial Derivatives','Currency & Deposits','Loans','Trade Credit & Advances','Other Investments']
df_by_region_main2 = pd.DataFrame(columns=df_temp_col_1.columns)

for x,y in calc_dict.items():
    # print(x,y)
    df_by_region_temp = df_temp_col_1[(df_temp_col_1['Region'].isin(y)) & (df_temp_col_1['Type'].isin(debt_row))]
    df_by_region_temp = df_by_region_temp.groupby(['Type']).sum()
    df_by_region_temp.loc[str(x) + ' Total'] = df_by_region_temp.sum()
    df_by_region_temp.loc['Other Investments'] = df_by_region_temp.loc[sum_rows2].sum()
    df_by_region_temp.reset_index(inplace = True)
    df_by_region_temp = df_by_region_temp[(~df_by_region_temp['Type'].isin(sum_rows2))] #####  the symbol of '~' use similar like notin, the oposite of isin. this is build in python operator
    df_by_region_temp['Type'] = df_by_region_temp['Type'].replace(debt_row, debt_row2)
    df_by_region_temp = df_by_region_temp.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(order2)}))
    df_by_region_temp['Region'] = x

    df_by_region_main2 = pd.concat([df_by_region_main2, df_by_region_temp], axis = 0)  

df_by_region_main2.reset_index(inplace = True, drop=True)
df_by_region_main2.insert(loc=0, column='Group', value='Liabilities')

df_by_region_main2#[(df_by_region_main2['Type'] == 'Other Investments')]
# ###################### this is for debt ######################

# ###################### this is for caq data ######################

# caq_data = df_temp_col_1[(df_temp_col_1['Type'].isin(df_init[(df_init['group'] == 'Current Account')]['desc'].to_list()[1:]))]
# caq_data_calc = caq_data.groupby(['Type']).sum()
# caq_data_calc.loc['Current Account Balance'] = caq_data_calc.sum()
# caq_data_calc['Region'] = 'Asia-Pacific'
# caq_data_calc.reset_index(inplace=True)
# rename_to = ['Goods Trade', 'Services Trade','Primary Income','Secondary Income',]
# rename_from = ['BoP: Current Account: Goods','BoP: Current Account: Services','BoP: Current Account: Primary Income','BoP: Current Account: Secondary Income',]
# caq_data_calc['Type'] = caq_data_calc['Type'].replace(rename_from, rename_to)
# caq_data_calc = caq_data_calc.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(rename_to)}))
# caq_data_calc.reset_index(drop=True, inplace=True)
# caq_data_calc.insert(loc=0, column='Group', value='Current Account')

# ###################### this is for caq data ######################

# df_main = pd.concat([df_by_region_main, df_by_region_main2, caq_data_calc], axis = 0) ## combine
# df_main.reset_index(drop=True, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13864\1850059041.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_by_region_main2 = pd.concat([df_by_region_main2, df_by_region_temp], axis = 0)

,Group,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,Liabilities,Other Investments,Asia-Pacific,67.550889,7.044588e+01,75.553523,80.238407,81.538383,178.054028,1.722052e+02,173.980331,175.386103,177.748953,168.053657,0,0
1,Liabilities,FDI Liabilities,Asia-Pacific,8211.953720,8.274635e+03,8246.766729,9050.226884,9534.195237,9870.240621,9.847562e+03,10042.010960,10185.504408,10531.540784,10645.730902,0,0
2,Liabilities,Financial Derivative Liabilities,Asia-Pacific,256.804296,2.446795e+02,320.835405,350.282109,304.405608,301.816960,4.573018e+02,486.897024,491.133384,422.469582,413.882560,0,0
3,Liabilities,Currency and Deposits Liabilities,Asia-Pacific,2702.868810,2.722472e+03,2750.602404,2917.642670,3070.920631,3084.988095,3.023057e+03,2944.556503,2878.583383,2953.951722,2779.888292,0,0
4,Liabilities,Loans Liabilities,Asia-Pacific,1599.125414,1.601866e+03,1625.557243,1641.335048,1698.341651,1690.597626,1.617004e+03,1615.502697,1663.974501,1654.389858,1632.546800,0,0
5,Liabilities,Trade Credits and Advances Liabilities,Asia-Pacific,725.723748,7.325734e+02,693.431264,742.259260,775.841444,836.245192,8.401963e+02,828.967007,791.944175,820.930619,722.854679,0,0
6,Liabilities,Portfolio Debt Liabilities,Asia-Pacific,1336.032646,1.410516e+03,1431.157814,1662.863329,1782.984059,1901.868720,1.792263e+03,1792.044677,1758.563085,1865.639569,1954.315924,0,0
7,Liabilities,Portfolio Equity Liabilities,Asia-Pacific,3076.208666,3.144753e+03,3073.090542,3788.894039,4135.344193,4001.421249,3.316351e+03,3246.447258,3485.615139,3409.902864,2831.987641,0,0
8,Liabilities,Asia-Pacific Total,Asia-Pacific,17976.268189,1.820194e+04,18216.994925,20233.741746,21383.571206,21865.232490,2.106594e+04,21130.406457,21430.704178,21836.573950,21149.260455,0,0
9,Liabilities,Other Investments,Asian Advance Economies,30.948839,3.302105e+01,37.262841,38.949565,34.738061,53.556382,5.087216e+01,51.191969,52.474942,54.312748,45.104205,0,0
10,Liabilities,FDI Liabilities,Asian Advance Economies,4016.557066,4.157946e+03,4138.250369,4423.964304,4687.365221,4789.072136,4.819767e+03,4944.964796,5140.790908,5383.961568,5543.922540,0,0
11,Liabilities,Financial Derivative Liabilities,Asian Advance Economies,242.927223,2.299603e+02,294.919048,324.088129,287.323272,284.466990,4.263783e+02,454.708254,452.559809,390.133134,370.744246,0,0
12,Liabilities,Currency and Deposits Liabilities,Asian Advance Economies,2025.681095,2.059155e+03,2051.371754,2151.328631,2210.968125,2248.886655,2.206525e+03,2179.860558,2099.624362,2201.130162,2026.245637,0,0
13,Liabilities,Loans Liabilities,Asian Advance Economies,588.515237,6.024763e+02,634.112078,667.067746,701.014636,709.896163,7.225711e+02,698.938900,730.054898,730.450056,694.777203,0,0
14,Liabilities,Trade Credits and Advances Liabilities,Asian Advance Economies,233.278632,2.248908e+02,231.422657,231.779877,236.778975,257.646403,2.660147e+02,274.911358,254.258045,261.192083,168.580446,0,0
15,Liabilities,Portfolio Debt Liabilities,Asian Advance Economies,415.718894,4.221768e+02,434.375677,466.189761,518.129735,570.638525,5.851634e+02,636.393985,649.841123,686.803189,689.168835,0,0
16,Liabilities,Portfolio Equity Liabilities,Asian Advance Economies,1680.839669,1.708245e+03,1758.928014,2106.965181,2339.687612,2218.689322,1.696654e+03,1699.563307,1942.157368,1969.694832,1333.876632,0,0
17,Liabilities,Asian Advance Economies Total,Asian Advance Economies,9234.466655,9.437871e+03,9580.642437,10410.333194,11016.005636,11132.852576,1.077395e+04,10940.533128,11321.761454,11677.677773,10872.419745,0,0
18,Liabilities,Other Investments,ASEAN5 Economies,8.069800,7.971883e+00,8.105778,8.450725,8.395446,26.362527,2.511251e+01,25.038380,25.228773,25.293813,25.232506,0,0
19,Liabilities,FDI Liabilities,ASEAN5 Economies,796.609606,8.220112e+02,789.268715,852.066414,854.335346,894.296190,8.968912e+02,934.681584,949.331017,978.573810,979.797630,0,0
20,Liabilities,Financial Derivative Liabilities,ASEAN5 Economies,6.209563,8.214602e+00,13.913373,13.319418,8.383027,6.919664,1.256229e+01,13.992250,15.399678,12.907305,13.615263,0,0
21,Liabilities,Currency and Deposits Liabilities,ASEAN5 Economies,92.178506,9.571182e+01,96.240184,90.412440,88.733366,88.596697,9.444504e+01,98.976778,98.869919,103.240837,104.368459,0,0
22,Liabilities,Loans Liabilities,ASEAN5 Economies,276.995770,2.845329e+02,289.626372,310.123739,296.332869,296.634329,2.877098e+02,296.793149,293.487117,310.992859,306.678851,0,0
23,Liabilities,Trade Credits and Advances Liabilities,ASEAN5 Economies,36.022192,3.543044e+01,32.899157,34.935911,38.318170,41.334469,4.741282e+01,45.222491,44.494252,43.995765,46.477401,0,0
24,Liabilities,Portfolio Debt Liabilities,ASEAN5 Economies,342.082216,3.626506e+02,366.618716,392.437246,408.283908,406.915347,3.853035e+02,382.543170,384.173970,387.889030,388.103512,0,0
25,Liabilities,Portfolio Equity Liabilities,ASEAN5 Economies,351.487176,3.367706e+02,244.844077,250.504847,259.659717,271.201223,2.490226e+02,272.267760,255.349353,257.724731,237.529011,0,0
26,Liabilities,ASEAN5 Economies Total,ASEAN5 Economies,1909.654831,1.953294e+03,1841.516371,1952.250740,1962.441849,2032.260447,1.998460e+03,2069.515563,2066.334080,2120.618149,2101.802633,0,0
27,Liabilities,Other Investments,Asian EDMEs,0.828895,8.244915e-01,0.276207,0.289172,0.286392,0.823219,7.809799e-01,0.782781,0.782328,0.496019,0.486287,0,0
28,Liabilities,FDI Liabilities,Asian EDMEs,67.626451,7.132324e+01,60.708696,62.844025,66.277261,69.288884,7.161327e+01,75.067641,78.001942,79.116527,82.103743,0,0
29,Liabilities,Financial Derivative Liabilities,Asian EDMEs,0.000050,5.080300e-07,0.000613,0.000006,0.000071,0.000021,5.400000e-10,0.000672,0.000112,0.000094,0.002786,0,0
30,Liabilities,Currency and Deposits Liabilities,Asian EDMEs,6.544135,7.723825e+00,6.150406,6.457288,6.690800,7.009922,7.025261e+00,6.960389,6.785890,5.969380,5.011088,0,0
31,Liabilities,Loans Liabilities,Asian EDMEs,58.627795,6.076248e+01,32.657692,34.955587,36.399787,37.696820,3.879118e+01,39.965253,40.872603,31.707520,30.031713,0,0
32,Liabilities,Trade Credits and Advances Liabilities,Asian EDMEs,2.891776,2.692957e+00,1.007081,1.025895,1.548538,1.328602,2.850465e+00,1.642351,1.774737,1.406419,1.520279,0,0
33,Liabilities,Portfolio Debt Liabilities,Asian EDMEs,21.775403,2.129300e+01,4.242247,4.560156,4.491934,4.433446,3.738659e+00,3.345611,3.061805,2.529574,2.459147,0,0
34,Liabilities,Portfolio Equity Liabilities,Asian EDMEs,0.728436,1.135018e+00,0.079475,0.085101,0.102384,0.111720,1.117583e-01,0.152149,0.203560,0.173621,0.212004,0,0
35,Liabilities,Asian EDMEs Total,Asian EDMEs,159.022942,1.657550e+02,105.122418,110.217230,115.797168,120.692634,1.249116e+02,127.916847,131.482976,121.399155,121.827047,0,0
36,Liabilities,Other Investments,China,22.172735,2.312722e+01,24.435825,26.819185,32.443802,74.151672,7.346762e+01,74.944636,74.890237,75.444665,75.464571,0,0
37,Liabilities,FDI Liabilities,China,2913.548658,2.796396e+03,2839.289329,3231.224732,3432.542034,3603.453434,3.542093e+03,3576.613288,3485.102736,3553.134827,3487.729437,0,0
38,Liabilities,Financial Derivative Liabilities,China,7.667459,6.504597e+00,12.002371,12.874556,8.699238,10.430285,1.836125e+01,18.195849,23.173785,19.429049,29.520263,0,0
39,Liabilities,Currency and Deposits Liabilities,China,441.666135,4.245258e+02,462.322424,525.933417,621.749572,596.992661,5.786702e+02,522.626459,529.234044,494.285224,483.635194,0,0
40,Liabilities,Loans Liabilities,China,479.904099,4.604718e+02,476.902343,441.393925,473.648363,449.491113,3.751631e+02,383.235235,392.682764,366.036711,375.888348,0,0
41,Liabilities,Trade Credits and Advances Liabilities,China,346.300000,3.643500e+02,324.100000,371.900000,397.441999,422.842000,4.011000e+02,382.600000,372.100000,391.100000,379.700000,0,0
42,Liabilities,Portfolio Debt Liabilities,China,461.441130,5.028583e+02,528.156269,695.125859,744.495338,809.112036,7.084619e+02,665.932393,615.875150,680.523475,758.210391,0,0
43,Liabilities,Portfolio Equity Liabilities,China,891.991858,9.497426e+02,930.278174,1260.709271,1359.691640,1338.624917,1.235087e+03,1133.994596,1134.976727,1021.103669,1099.472081,0,0
44,Liabilities,China Total,China,5564.692073,5.527976e+03,5597.486735,6565.980946,7070.711987,7305.098118,6.932403e+03,6758.142456,6628.035443,6601.057619,6689.620285,0,0
45,Liabilities,Other Investments,India,5.530621,5.501237e+00,5.472872,5.729760,5.674682,23.160228,2.197189e+01,22.022564,22.009822,22.201708,21.766088,0,0
46,Liabilities,FDI Liabilities,India,417.611939,4.269590e+02,419.249621,480.127410,493.675376,514.129977,5.171983e+02,510.683651,532.277806,536.754052,552.177552,0,0
47,Liabilities,Financial Derivative Liabilities,India,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0,0
48,Liabilities,Currency and Deposits Liabilities,India,136.798940,1.353562e+02,134.517637,143.510893,142.778767,143.502160,1.363917e+02,136.132318,144.069169,149.326119,160.627913,0,0
49,Liabilities,Loans Liabilities,India,195.082513,1.936228e+02,192.258757,187.794051,190.945995,196.879201,1.927690e+02,196.570161,206.877118,215.202712,225.170686,0,0
50,Liabilities,Trade Credits and Advances Liabilities,India,107.231148,1.052092e+02,104.002369,102.617578,101.753762,113.093718,1.228183e+02,124.590807,119.317142,123.236351,126.576554,0,0
51,Liabilities,Portfolio Debt Liabilities,India,95.015003,1.015370e+02,97.764904,104.550306,107.583144,110.769365,1.095954e+02,103.829517,105.611037,107.894301,116.374040,0,0
52,Liabilities,Portfolio Equity Liabilities,India,151.161526,1.488594e+02,138.960803,170.629639,176.202840,172.794067,1.354759e+02,140.469446,152.928131,161.206011,160.897912,0,0
53,Liabilities,India Total,India,1108.431689,1.117045e+03,1092.226964,1194.959636,1218.614566,1274.328715,1.236220e+03,1234.298465,1283.090225,1315.821254,1363.590745,0,0

In [175]:
tw_col1 = df_all_annual_2.columns[4:][~df_all_annual_2.columns[4:].isin(df_tw.columns[4:])]
tw_col2 = {x.year:x for x in df_tw.columns[4:]}

for x in tw_col1:
    year = x.year
    if year in list(tw_col2.keys()):
        df_tw[x] = tw_col2[year]
    else:
        df_tw[x] = None
df_tw[df_tw.columns[4:12]][(df_tw['Type'] == 'IIP: Assets')]

# df_tw.loc[:,tw_col1] = None
# df_tw = df_tw[df_tw.columns[:4].to_list() +df_tw.columns[4:].sort_values().to_list()]
# df_tw
# df_temp_col_1.drop(index=tw_index.index.to_list(), inplace=True)
# df_temp_col_1 = pd.concat([df_temp_col_1, tw_index], axis = 0)

# df_temp_col_1.sort_values(by=['Type', 'Region'], inplace=True)
# df_temp_col_1.reset_index(drop=True, inplace=True)
# df_temp_col_1

,2019-12-01 00:00:00,2020-12-01 00:00:00,2021-12-01 00:00:00,2022-12-01 00:00:00,2023-12-01 00:00:00,2019-03-01 00:00:00,2019-06-01 00:00:00,2019-09-01 00:00:00
0,2281141,2519168,2728856,2662530,2909567,2019-12-01,2019-12-01,2019-12-01

In [178]:
df_temp_col_1[(df_temp_col_1['Region'] == 'Taiwan')]

,Type,Region,Unit,Last Update Time,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
16,IIP: Assets,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,2281141.0,2020-12-01 00:00:00,2519168.0,2021-12-01 00:00:00,2728856.0,2022-12-01 00:00:00,2662530.0,2023-12-01 00:00:00,2909567.0,NaN,NaN,NaN
35,IIP: Assets: Direct Investment,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,368040.0,2020-12-01 00:00:00,400725.0,2021-12-01 00:00:00,450961.0,2022-12-01 00:00:00,450919.0,2023-12-01 00:00:00,500135.0,NaN,NaN,NaN
54,IIP: Assets: Direct Investment: Debt Instruments,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,8096.0,2020-12-01 00:00:00,8654.0,2021-12-01 00:00:00,9528.0,2022-12-01 00:00:00,11289.0,2023-12-01 00:00:00,11058.0,NaN,NaN,NaN
73,IIP: Assets: Direct Investment: Equity,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,359944.0,2020-12-01 00:00:00,392071.0,2021-12-01 00:00:00,441433.0,2022-12-01 00:00:00,439630.0,2023-12-01 00:00:00,489077.0,NaN,NaN,NaN
92,IIP: Assets: Financial Derivatives & Employee ...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,5949.0,2020-12-01 00:00:00,8957.0,2021-12-01 00:00:00,4658.0,2022-12-01 00:00:00,9027.0,2023-12-01 00:00:00,9773.0,NaN,NaN,NaN
111,IIP: Assets: Official Reserve Assets,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,483240.0,2020-12-01 00:00:00,535327.0,2021-12-01 00:00:00,553984.0,2022-12-01 00:00:00,559956.0,2023-12-01 00:00:00,575597.0,NaN,NaN,NaN
130,IIP: Assets: Other Investment,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,404911.0,2020-12-01 00:00:00,420507.0,2021-12-01 00:00:00,430940.0,2022-12-01 00:00:00,427681.0,2023-12-01 00:00:00,438227.0,NaN,NaN,NaN
149,IIP: Assets: Other Investment: Currency & Depo...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,208183.0,2020-12-01 00:00:00,225952.0,2021-12-01 00:00:00,229403.0,2022-12-01 00:00:00,230985.0,2023-12-01 00:00:00,238765.0,NaN,NaN,NaN
168,"IIP: Assets: Other Investment: Insurance, Pens...",Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,IIP: Assets: Other Investment: Loans,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,114431.0,2020-12-01 00:00:00,119735.0,2021-12-01 00:00:00,124904.0,2022-12-01 00:00:00,123928.0,2023-12-01 00:00:00,120185.0,NaN,NaN,NaN
206,IIP: Assets: Other Investment: Other Accounts ...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,17993.0,2020-12-01 00:00:00,18999.0,2021-12-01 00:00:00,18813.0,2022-12-01 00:00:00,18436.0,2023-12-01 00:00:00,15574.0,NaN,NaN,NaN
225,IIP: Assets: Other Investment: Other Equity,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,80.0,2020-12-01 00:00:00,83.0,2021-12-01 00:00:00,81.0,2022-12-01 00:00:00,77.0,2023-12-01 00:00:00,78.0,NaN,NaN,NaN
244,IIP: Assets: Other Investment: Trade Credit & ...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,64224.0,2020-12-01 00:00:00,55738.0,2021-12-01 00:00:00,57739.0,2022-12-01 00:00:00,54255.0,2023-12-01 00:00:00,63625.0,NaN,NaN,NaN
263,IIP: Assets: Portfolio Investment,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,1019001.0,2020-12-01 00:00:00,1153652.0,2021-12-01 00:00:00,1288313.0,2022-12-01 00:00:00,1214947.0,2023-12-01 00:00:00,1385835.0,NaN,NaN,NaN
282,IIP: Assets: Portfolio Investment: Debt Securi...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,732543.0,2020-12-01 00:00:00,831903.0,2021-12-01 00:00:00,899060.0,2022-12-01 00:00:00,895604.0,2023-12-01 00:00:00,992038.0,NaN,NaN,NaN
301,IIP: Assets: Portfolio Investment: Equity,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,286458.0,2020-12-01 00:00:00,321749.0,2021-12-01 00:00:00,389253.0,2022-12-01 00:00:00,319343.0,2023-12-01 00:00:00,393797.0,NaN,NaN,NaN
320,IIP: Liabilities,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,907708.0,2020-12-01 00:00:00,1120857.0,2021-12-01 00:00:00,1308241.0,2022-12-01 00:00:00,991146.0,2023-12-01 00:00:00,1174265.0,NaN,NaN,NaN
339,IIP: Liabilities: Direct Investment,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,98552.0,2020-12-01 00:00:00,110746.0,2021-12-01 00:00:00,127064.0,2022-12-01 00:00:00,124426.0,2023-12-01 00:00:00,136586.0,NaN,NaN,NaN
358,IIP: Liabilities: Direct Investment: Debt Inst...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,1609.0,2020-12-01 00:00:00,2134.0,2021-12-01 00:00:00,4925.0,2022-12-01 00:00:00,8868.0,2023-12-01 00:00:00,9787.0,NaN,NaN,NaN
377,IIP: Liabilities: Direct Investment: Equity,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,96943.0,2020-12-01 00:00:00,108612.0,2021-12-01 00:00:00,122139.0,2022-12-01 00:00:00,115558.0,2023-12-01 00:00:00,126799.0,NaN,NaN,NaN
396,IIP: Liabilities: Financial Derivatives & Empl...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,5627.0,2020-12-01 00:00:00,7963.0,2021-12-01 00:00:00,4106.0,2022-12-01 00:00:00,10455.0,2023-12-01 00:00:00,8816.0,NaN,NaN,NaN
415,IIP: Liabilities: Other Investment,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,305759.0,2020-12-01 00:00:00,322508.0,2021-12-01 00:00:00,341415.0,2022-12-01 00:00:00,323822.0,2023-12-01 00:00:00,317963.0,NaN,NaN,NaN
434,IIP: Liabilities: Other Investment: Currency &...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,141588.0,2020-12-01 00:00:00,143724.0,2021-12-01 00:00:00,165707.0,2022-12-01 00:00:00,157412.0,2023-12-01 00:00:00,149104.0,NaN,NaN,NaN
453,"IIP: Liabilities: Other Investment: Insurance,...",Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,IIP: Liabilities: Other Investment: Loans,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,64594.0,2020-12-01 00:00:00,65670.0,2021-12-01 00:00:00,69388.0,2022-12-01 00:00:00,56480.0,2023-12-01 00:00:00,67838.0,NaN,NaN,NaN
491,IIP: Liabilities: Other Investment: Other Acco...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,8379.0,2020-12-01 00:00:00,12910.0,2021-12-01 00:00:00,6854.0,2022-12-01 00:00:00,6678.0,2023-12-01 00:00:00,8110.0,NaN,NaN,NaN
510,IIP: Liabilities: Other Investment: Other Equity,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,0.0,2020-12-01 00:00:00,0.0,2021-12-01 00:00:00,0.0,2022-12-01 00:00:00,0.0,2023-12-01 00:00:00,0.0,NaN,NaN,NaN
529,IIP: Liabilities: Other Investment: SDRs,Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,IIP: Liabilities: Other Investment: Trade Cred...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,91198.0,2020-12-01 00:00:00,100204.0,2021-12-01 00:00:00,99466.0,2022-12-01 00:00:00,103252.0,2023-12-01 00:00:00,92911.0,NaN,NaN,NaN
567,IIP: Liabilities: Portfolio Investment,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,497770.0,2020-12-01 00:00:00,679640.0,2021-12-01 00:00:00,835656.0,2022-12-01 00:00:00,532443.0,2023-12-01 00:00:00,710900.0,NaN,NaN,NaN
586,IIP: Liabilities: Portfolio Investment: Debt S...,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,2386.0,2020-12-01 00:00:00,2759.0,2021-12-01 00:00:00,4121.0,2022-12-01 00:00:00,2769.0,2023-12-01 00:00:00,2712.0,NaN,NaN,NaN
605,IIP: Liabilities: Portfolio Investment: Equity,Taiwan,USD mn,2024-06-14,2019-12-01 00:00:00,495384.0,2020-12-01 00:00:00,676881.0,2021-12-01 00:00:00,831535.0,2022-12-01 00:00:00,529674.0,2023-12-01 00:00:00,708188.0,NaN,NaN,NaN

In [156]:
tw_col2

[datetime.datetime(2019, 12, 1, 0, 0),
 datetime.datetime(2019, 12, 1, 0, 0),
 datetime.datetime(2019, 12, 1, 0, 0),
 datetime.datetime(2019, 12, 1, 0, 0),
 datetime.datetime(2020, 12, 1, 0, 0),
 datetime.datetime(2020, 12, 1, 0, 0),
 datetime.datetime(2020, 12, 1, 0, 0),
 datetime.datetime(2020, 12, 1, 0, 0),
 datetime.datetime(2021, 12, 1, 0, 0),
 datetime.datetime(2021, 12, 1, 0, 0),
 datetime.datetime(2021, 12, 1, 0, 0),
 datetime.datetime(2021, 12, 1, 0, 0),
 datetime.datetime(2022, 12, 1, 0, 0),
 datetime.datetime(2022, 12, 1, 0, 0),
 datetime.datetime(2022, 12, 1, 0, 0),
 datetime.datetime(2022, 12, 1, 0, 0),
 datetime.datetime(2023, 12, 1, 0, 0),
 datetime.datetime(2023, 12, 1, 0, 0),
 datetime.datetime(2023, 12, 1, 0, 0),
 datetime.datetime(2023, 12, 1, 0, 0)]

In [91]:
tw_index = df_temp_col_1[(df_temp_col_1['Region'] =='Taiwan')].copy()

tw_col1 = [x for x in tw_index.columns[4:] if x[:2] == '1H']
tw_col2 = [x for x in tw_index.columns[4:] if x[:2] == '2H']
for x, y in zip(tw_col1, tw_col2):
    tw_index[x] = tw_index[y]
tw_index.index

Index([ 16,  35,  54,  73,  92, 111, 130, 149, 168, 187, 206, 225, 244, 263,
       282, 301, 320, 339, 358, 377, 396, 415, 434, 453, 472, 491, 510, 529,
       548, 567, 586, 605],
      dtype='int64')

In [74]:
df_temp_col_1[(df_temp_col_1['Region'] =='Taiwan')]

,Type,Region,Unit,Last Update Time,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
16,IIP: Assets,Taiwan,USD mn,2024-06-14,NaN,2281.141,NaN,2519.168,NaN,2728.856,NaN,2662.530,NaN,2909.567,NaN,NaN,NaN
35,IIP: Assets: Direct Investment,Taiwan,USD mn,2024-06-14,NaN,368.040,NaN,400.725,NaN,450.961,NaN,450.919,NaN,500.135,NaN,NaN,NaN
54,IIP: Assets: Direct Investment: Debt Instruments,Taiwan,USD mn,2024-06-14,NaN,8.096,NaN,8.654,NaN,9.528,NaN,11.289,NaN,11.058,NaN,NaN,NaN
73,IIP: Assets: Direct Investment: Equity,Taiwan,USD mn,2024-06-14,NaN,359.944,NaN,392.071,NaN,441.433,NaN,439.630,NaN,489.077,NaN,NaN,NaN
92,IIP: Assets: Financial Derivatives & Employee ...,Taiwan,USD mn,2024-06-14,NaN,5.949,NaN,8.957,NaN,4.658,NaN,9.027,NaN,9.773,NaN,NaN,NaN
111,IIP: Assets: Official Reserve Assets,Taiwan,USD mn,2024-06-14,NaN,483.240,NaN,535.327,NaN,553.984,NaN,559.956,NaN,575.597,NaN,NaN,NaN
130,IIP: Assets: Other Investment,Taiwan,USD mn,2024-06-14,NaN,404.911,NaN,420.507,NaN,430.940,NaN,427.681,NaN,438.227,NaN,NaN,NaN
149,IIP: Assets: Other Investment: Currency & Depo...,Taiwan,USD mn,2024-06-14,NaN,208.183,NaN,225.952,NaN,229.403,NaN,230.985,NaN,238.765,NaN,NaN,NaN
168,"IIP: Assets: Other Investment: Insurance, Pens...",Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,IIP: Assets: Other Investment: Loans,Taiwan,USD mn,2024-06-14,NaN,114.431,NaN,119.735,NaN,124.904,NaN,123.928,NaN,120.185,NaN,NaN,NaN
206,IIP: Assets: Other Investment: Other Accounts ...,Taiwan,USD mn,2024-06-14,NaN,17.993,NaN,18.999,NaN,18.813,NaN,18.436,NaN,15.574,NaN,NaN,NaN
225,IIP: Assets: Other Investment: Other Equity,Taiwan,USD mn,2024-06-14,NaN,0.080,NaN,0.083,NaN,0.081,NaN,0.077,NaN,0.078,NaN,NaN,NaN
244,IIP: Assets: Other Investment: Trade Credit & ...,Taiwan,USD mn,2024-06-14,NaN,64.224,NaN,55.738,NaN,57.739,NaN,54.255,NaN,63.625,NaN,NaN,NaN
263,IIP: Assets: Portfolio Investment,Taiwan,USD mn,2024-06-14,NaN,1019.001,NaN,1153.652,NaN,1288.313,NaN,1214.947,NaN,1385.835,NaN,NaN,NaN
282,IIP: Assets: Portfolio Investment: Debt Securi...,Taiwan,USD mn,2024-06-14,NaN,732.543,NaN,831.903,NaN,899.060,NaN,895.604,NaN,992.038,NaN,NaN,NaN
301,IIP: Assets: Portfolio Investment: Equity,Taiwan,USD mn,2024-06-14,NaN,286.458,NaN,321.749,NaN,389.253,NaN,319.343,NaN,393.797,NaN,NaN,NaN
320,IIP: Liabilities,Taiwan,USD mn,2024-06-14,NaN,907.708,NaN,1120.857,NaN,1308.241,NaN,991.146,NaN,1174.265,NaN,NaN,NaN
339,IIP: Liabilities: Direct Investment,Taiwan,USD mn,2024-06-14,NaN,98.552,NaN,110.746,NaN,127.064,NaN,124.426,NaN,136.586,NaN,NaN,NaN
358,IIP: Liabilities: Direct Investment: Debt Inst...,Taiwan,USD mn,2024-06-14,NaN,1.609,NaN,2.134,NaN,4.925,NaN,8.868,NaN,9.787,NaN,NaN,NaN
377,IIP: Liabilities: Direct Investment: Equity,Taiwan,USD mn,2024-06-14,NaN,96.943,NaN,108.612,NaN,122.139,NaN,115.558,NaN,126.799,NaN,NaN,NaN
396,IIP: Liabilities: Financial Derivatives & Empl...,Taiwan,USD mn,2024-06-14,NaN,5.627,NaN,7.963,NaN,4.106,NaN,10.455,NaN,8.816,NaN,NaN,NaN
415,IIP: Liabilities: Other Investment,Taiwan,USD mn,2024-06-14,NaN,305.759,NaN,322.508,NaN,341.415,NaN,323.822,NaN,317.963,NaN,NaN,NaN
434,IIP: Liabilities: Other Investment: Currency &...,Taiwan,USD mn,2024-06-14,NaN,141.588,NaN,143.724,NaN,165.707,NaN,157.412,NaN,149.104,NaN,NaN,NaN
453,"IIP: Liabilities: Other Investment: Insurance,...",Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,IIP: Liabilities: Other Investment: Loans,Taiwan,USD mn,2024-06-14,NaN,64.594,NaN,65.670,NaN,69.388,NaN,56.480,NaN,67.838,NaN,NaN,NaN
491,IIP: Liabilities: Other Investment: Other Acco...,Taiwan,USD mn,2024-06-14,NaN,8.379,NaN,12.910,NaN,6.854,NaN,6.678,NaN,8.110,NaN,NaN,NaN
510,IIP: Liabilities: Other Investment: Other Equity,Taiwan,USD mn,2024-06-14,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,NaN,NaN,NaN
529,IIP: Liabilities: Other Investment: SDRs,Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,IIP: Liabilities: Other Investment: Trade Cred...,Taiwan,USD mn,2024-06-14,NaN,91.198,NaN,100.204,NaN,99.466,NaN,103.252,NaN,92.911,NaN,NaN,NaN
567,IIP: Liabilities: Portfolio Investment,Taiwan,USD mn,2024-06-14,NaN,497.770,NaN,679.640,NaN,835.656,NaN,532.443,NaN,710.900,NaN,NaN,NaN
586,IIP: Liabilities: Portfolio Investment: Debt S...,Taiwan,USD mn,2024-06-14,NaN,2.386,NaN,2.759,NaN,4.121,NaN,2.769,NaN,2.712,NaN,NaN,NaN
605,IIP: Liabilities: Portfolio Investment: Equity,Taiwan,USD mn,2024-06-14,NaN,495.384,NaN,676.881,NaN,831.535,NaN,529.674,NaN,708.188,NaN,NaN,NaN

In [56]:
df_all_annual_2

,Type,Region,Unit,Last Update Time,2019-03-01 00:00:00,2019-06-01 00:00:00,2019-09-01 00:00:00,2019-12-01 00:00:00,2020-03-01 00:00:00,2020-06-01 00:00:00,...,2023-06-01 00:00:00,2023-09-01 00:00:00,2023-12-01 00:00:00,2024-03-01 00:00:00,2024-06-01 00:00:00,2024-09-01 00:00:00,2024-12-01 00:00:00,2025-03-01 00:00:00,2025-06-01 00:00:00,2025-09-01 00:00:00
0,IIP: Assets,Brunei,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,USD mn,2024-10-24,2.417597e+04,2.507544e+04,2.677201e+04,2.862880e+04,2.878970e+04,3.065766e+04,...,3.005370e+04,3.036972e+04,3.360136e+04,3.539776e+04,3.580391e+04,NaN,NaN,NaN,NaN,NaN
2,IIP: Assets,China,USD mn,2024-10-24,7.503297e+06,7.592054e+06,7.613220e+06,7.846418e+06,7.777337e+06,8.014177e+06,...,9.366431e+06,9.303764e+06,9.581683e+06,9.664292e+06,9.792861e+06,NaN,NaN,NaN,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),USD mn,2024-10-24,5.678545e+06,5.533903e+06,5.438994e+06,5.641767e+06,5.543582e+06,5.706870e+06,...,6.112216e+06,6.123758e+06,6.183809e+06,6.268514e+06,6.470570e+06,NaN,NaN,NaN,NaN,NaN
4,IIP: Assets,India,USD mn,2024-10-24,6.421384e+05,6.625843e+05,6.702019e+05,6.980954e+05,7.168001e+05,7.487695e+05,...,9.407915e+05,9.440507e+05,9.916381e+05,1.026863e+06,1.048228e+06,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,IIP: Liabilities: Portfolio Investment: Equity,South Korea,USD mn,2024-09-26,4.697642e+05,4.677524e+05,4.474341e+05,4.975231e+05,3.733060e+05,4.389853e+05,...,5.192382e+05,4.861519e+05,5.655252e+05,5.988869e+05,6.077568e+05,NaN,NaN,NaN,NaN,NaN
585,IIP: Liabilities: Portfolio Investment: Equity,Sri Lanka,USD mn,2020-08-27,7.385835e+02,6.513650e+02,9.751852e+02,1.055937e+03,1.990319e+02,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,IIP: Liabilities: Portfolio Investment: Equity,Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,IIP: Liabilities: Portfolio Investment: Equity,Thailand,USD mn,2024-10-24,1.182496e+05,1.275366e+05,1.200384e+05,1.161480e+05,7.432922e+04,8.907222e+04,...,9.603894e+04,9.113267e+04,9.005005e+04,8.106438e+04,7.595472e+04,NaN,NaN,NaN,NaN,NaN
588,IIP: Liabilities: Portfolio Investment: Equity,Vietnam,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.concat([df_temp_col_1[df_temp_col_1.columns[:2]][(df_temp_col_1['Type']=='IIP: Assets')], df_temp_col_1[df_temp_col_1.columns[2:]][(df_temp_col_1['Type']=='IIP: Assets')]/1000], axis=1)

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,IIP: Assets,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,0.049251,0.055401,0.059447,0.067575,0.062060,0.058532,0.057874,0.055339,0.060065,0.063971,0.071202,NaN,NaN
2,IIP: Assets,China,15.095351,15.459637,15.791514,17.172499,19.294797,18.956215,18.734448,18.186327,18.808894,18.885447,19.457153,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),11.212448,11.080761,11.250453,12.229871,12.965785,12.824832,12.578471,11.957092,12.259264,12.307567,12.739084,NaN,NaN
4,IIP: Assets,India,1.304723,1.368297,1.465570,1.655428,1.751156,1.859408,1.835778,1.748168,1.856972,1.935689,2.075091,NaN,NaN
5,IIP: Assets,Indonesia,0.724324,0.742283,0.750765,0.795300,0.825886,0.862788,0.869213,0.889769,0.931945,0.949373,0.977144,NaN,NaN
6,IIP: Assets,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,IIP: Assets,Malaysia,0.847109,0.855538,0.871443,0.925038,0.973585,1.005236,0.995476,0.987248,1.029305,1.035196,1.060096,NaN,NaN
8,IIP: Assets,Mongolia,0.013430,0.014119,0.014048,0.015230,0.016772,0.016180,0.013312,0.013112,0.014918,0.016978,0.017907,NaN,NaN
9,IIP: Assets,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,IIP: Assets,Nepal,0.019477,0.020144,0.022307,0.026409,0.025878,0.022840,0.021159,0.021425,0.024302,NaN,NaN,NaN,NaN
11,IIP: Assets,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,IIP: Assets,Philippines,0.371129,0.387572,0.404810,0.452345,0.464280,0.479457,0.468781,0.450068,0.469629,0.475559,0.488274,NaN,NaN
13,IIP: Assets,Singapore,8.108652,8.493461,8.830425,9.617985,10.106776,10.301273,10.430777,10.381529,10.761805,11.027629,11.384588,NaN,NaN
14,IIP: Assets,South Korea,3.244444,3.378478,3.443196,3.803669,4.127257,4.378646,4.421323,4.360306,4.514950,4.578736,4.767737,NaN,NaN
15,IIP: Assets,Sri Lanka,0.027092,0.025914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,IIP: Assets,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IIP: Assets,Thailand,1.023743,1.068453,1.106302,1.189434,1.207889,1.219443,1.202522,1.153967,1.193595,1.194805,1.220727,NaN,NaN
18,IIP: Assets,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_temp_col_1[(df_temp_col_1['Type']=='IIP: Assets')]

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,IIP: Assets,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,49.251410,55.400812,59.447361,67.574788,62.060306,58.531766,57.874145,55.339257,60.064708,63.971080,71.201661,NaN,NaN
2,IIP: Assets,China,15095.351337,15459.637344,15791.513791,17172.498955,19294.796530,18956.214763,18734.448489,18186.327382,18808.894045,18885.446752,19457.153153,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),11212.448000,11080.761196,11250.452559,12229.870692,12965.785227,12824.831873,12578.470956,11957.092472,12259.263950,12307.567071,12739.083520,NaN,NaN
4,IIP: Assets,India,1304.722689,1368.297282,1465.569636,1655.427998,1751.156057,1859.408122,1835.778114,1748.168061,1856.971906,1935.688768,2075.091003,NaN,NaN
5,IIP: Assets,Indonesia,724.323817,742.283316,750.764564,795.300483,825.885523,862.788313,869.213043,889.768871,931.945167,949.372809,977.144050,NaN,NaN
6,IIP: Assets,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,IIP: Assets,Malaysia,847.108568,855.537747,871.443380,925.038211,973.584626,1005.236130,995.475752,987.248425,1029.305168,1035.195587,1060.095770,NaN,NaN
8,IIP: Assets,Mongolia,13.429910,14.118793,14.048275,15.229968,16.772060,16.179695,13.311752,13.111590,14.917649,16.977541,17.906857,NaN,NaN
9,IIP: Assets,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,IIP: Assets,Nepal,19.477411,20.144181,22.306943,26.408513,25.877809,22.840498,21.159289,21.425242,24.302349,NaN,NaN,NaN,NaN
11,IIP: Assets,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,IIP: Assets,Philippines,371.128762,387.571664,404.810398,452.345429,464.279759,479.457113,468.781182,450.068182,469.628998,475.558780,488.273864,NaN,NaN
13,IIP: Assets,Singapore,8108.651714,8493.461121,8830.424645,9617.984644,10106.775691,10301.273054,10430.776740,10381.529413,10761.805293,11027.628917,11384.588361,NaN,NaN
14,IIP: Assets,South Korea,3244.443647,3378.477662,3443.196033,3803.668909,4127.256536,4378.645920,4421.323445,4360.306353,4514.950047,4578.735634,4767.737438,NaN,NaN
15,IIP: Assets,Sri Lanka,27.091998,25.913793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,IIP: Assets,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IIP: Assets,Thailand,1023.743412,1068.453423,1106.302304,1189.434236,1207.888515,1219.443495,1202.521711,1153.966801,1193.594784,1194.804826,1220.726579,NaN,NaN
18,IIP: Assets,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_init

,group,short_title,desc
0,FDI Assets,FDI Assets,IIP: Assets: Direct Investment
1,FDI Assets,FDI Equity Assets,IIP: Assets: Direct Investment: Equity
2,FDI Assets,FDI Debt Assets,IIP: Assets: Direct Investment: Debt Instruments
3,Portfolio Assets,Portfolio Assets,IIP: Assets: Portfolio Investment
4,Portfolio Assets,Portfolio Equity Assets,IIP: Assets: Portfolio Investment: Equity
5,Portfolio Assets,Portfolio Debt Assets,IIP: Assets: Portfolio Investment: Debt Securi...
6,Financial Derivative Assets,Financial Derivative Assets,IIP: Assets: Financial Derivatives & Employee ...
7,Other Investment Assets,Other Investment Assets,IIP: Assets: Other Investment
8,Other Investment Assets,OI Equity Assets,IIP: Assets: Other Investment: Other Equity
9,Other Investment Assets,Currency and Deposits Assets,IIP: Assets: Other Investment: Currency & Depo...
10,Other Investment Assets,Loans Assets,IIP: Assets: Other Investment: Loans
11,Other Investment Assets,Insurance and Pension Assets,"IIP: Assets: Other Investment: Insurance, Pens..."
12,Other Investment Assets,Trade Credits and Advances Assets,IIP: Assets: Other Investment: Trade Credit & ...
13,Other Investment Assets,OI Others Assets,IIP: Assets: Other Investment: Other Accounts ...
14,Official Reserve Assets,Official Reserve Assets,IIP: Assets: Official Reserve Assets
15,International Investment Assets,International Investment Assets,IIP: Assets
16,FDI Liabilities,FDI Liabilities,IIP: Liabilities: Direct Investment
17,FDI Liabilities,FDI Equity Liabilities,IIP: Liabilities: Direct Investment: Equity
18,FDI Liabilities,FDI Debt Liabilities,IIP: Liabilities: Direct Investment: Debt Inst...
19,Portfolio Liabilities,Portfolio Liabilities,IIP: Liabilities: Portfolio Investment
20,Portfolio Liabilities,Portfolio Equity Liabilities,IIP: Liabilities: Portfolio Investment: Equity
21,Portfolio Liabilities,Portfolio Debt Liabilities,IIP: Liabilities: Portfolio Investment: Debt S...
22,Financial Derivative Liabilities,Financial Derivative Liabilities,IIP: Liabilities: Financial Derivatives & Empl...
23,Other Investment Liabilities,Other Investment Liabilities,IIP: Liabilities: Other Investment
24,Other Investment Liabilities,OI Equity Liabilities,IIP: Liabilities: Other Investment: Other Equity
25,Other Investment Liabilities,Currency and Deposits Liabilities,IIP: Liabilities: Other Investment: Currency &...
26,Other Investment Liabilities,Loans Liabilities,IIP: Liabilities: Other Investment: Loans
27,Other Investment Liabilities,Insurance and Pension Liabilities,"IIP: Liabilities: Other Investment: Insurance,..."
28,Other Investment Liabilities,Trade Credits and Advances Liabilities,IIP: Liabilities: Other Investment: Trade Cred...
29,Other Investment Liabilities,OI Others Liabilities,IIP: Liabilities: Other Investment: Other Acco...
30,Official Reserve Liabilities,Official Reserve Liabilities,IIP: Liabilities: Other Investment: SDRs
31,International Investment Liabilities,International Investment Liabilities,IIP: Liabilities

In [ ]:
###################### this is for equity ######################

asset_row = df_init.iloc[[0,4,5,6, 8, 9,10,11,12,13,14]]['desc'].to_list()
asset_row2 = ['Direct Investment', 'Portfolio Equity', 'Portfolio Debt','Financial Derivatives', 'Other Equity','Currency & Deposits','Loans','Insurance, Pension & Standardized Guarantee Schemes'
            ,'Trade Credit & Advances','Other Accounts Receivable','Reserve Assets', ]
sum_rows = df_init[(df_init['short_title'].isin(['OI Equity Assets','Insurance and Pension Assets','OI Others Assets',]))]['desc'].to_list()
order = ['Direct Investment','Portfolio Equity','Portfolio Debt','Financial Derivatives','Currency & Deposits','Loans','Trade Credit & Advances','Other Investments','Reserve Assets',]
df_by_region_main = pd.DataFrame(columns=df_temp_col_1.columns)

for x,y in calc_dict.items():
    # print(x,y)
    df_by_region_temp = df_temp_col_1[(df_temp_col_1['Region'].isin(y)) & (df_temp_col_1['Type'].isin(asset_row))]
    df_by_region_temp = df_by_region_temp.groupby(['Type']).sum()
    df_by_region_temp.loc[str(x) + ' Total'] = df_by_region_temp.sum()
    df_by_region_temp.loc['Other Investments'] = df_by_region_temp.loc[sum_rows].sum()
    df_by_region_temp.reset_index(inplace = True)
    df_by_region_temp = df_by_region_temp[(~df_by_region_temp['Type'].isin(sum_rows))] #####  the symbol of '~' use similar like notin, the oposite of isin. this is build in python operator
    df_by_region_temp['Type'] = df_by_region_temp['Type'].replace(asset_row, asset_row2)
    df_by_region_temp = df_by_region_temp.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(order)}))
    df_by_region_temp['Region'] = x

    df_by_region_main = pd.concat([df_by_region_main, df_by_region_temp], axis = 0)  


df_by_region_main.reset_index(inplace = True, drop=True)
df_by_region_main.insert(loc=0, column='Group', value='Assets')

###################### this is for equity ######################

###################### this is for debt ######################

debt_row = df_init.iloc[[20,24,25,26,28,29,30,31,32,33,34]]['desc'].to_list()
debt_row2 = ['Direct Investment', 'Portfolio Equity', 'Portfolio Debt','Financial Derivatives', 'Other Equity','Currency & Deposits','Loans','Insurance, Pension & Standardized Guarantee Schemes'
            ,'Trade Credit & Advances','Other Accounts Payable','SDR Liabilities', ]
sum_rows2 = df_init[(df_init['short_title'].isin(['OI Equity Liabilities', 'Insurance and Pension Liabilities', 'OI Others Liabilities', 'SDR Liabilities']))]['desc'].to_list()
order2 = ['Direct Investment','Portfolio Equity','Portfolio Debt','Financial Derivatives','Currency & Deposits','Loans','Trade Credit & Advances','Other Investments']
df_by_region_main2 = pd.DataFrame(columns=df_temp_col_1.columns)

for x,y in calc_dict.items():
    # print(x,y)
    df_by_region_temp = df_temp_col_1[(df_temp_col_1['Region'].isin(y)) & (df_temp_col_1['Type'].isin(debt_row))]
    df_by_region_temp = df_by_region_temp.groupby(['Type']).sum()
    df_by_region_temp.loc[str(x) + ' Total'] = df_by_region_temp.sum()
    df_by_region_temp.loc['Other Investments'] = df_by_region_temp.loc[sum_rows2].sum()
    df_by_region_temp.reset_index(inplace = True)
    df_by_region_temp = df_by_region_temp[(~df_by_region_temp['Type'].isin(sum_rows2))] #####  the symbol of '~' use similar like notin, the oposite of isin. this is build in python operator
    df_by_region_temp['Type'] = df_by_region_temp['Type'].replace(debt_row, debt_row2)
    df_by_region_temp = df_by_region_temp.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(order2)}))
    df_by_region_temp['Region'] = x

    df_by_region_main2 = pd.concat([df_by_region_main2, df_by_region_temp], axis = 0)  

df_by_region_main2.reset_index(inplace = True, drop=True)
df_by_region_main2.insert(loc=0, column='Group', value='Liabilities')

###################### this is for debt ######################

###################### this is for caq data ######################

caq_data = df_temp_col_1[(df_temp_col_1['Type'].isin(df_init[(df_init['group'] == 'Current Account')]['desc'].to_list()[1:]))]
caq_data_calc = caq_data.groupby(['Type']).sum()
caq_data_calc.loc['Current Account Balance'] = caq_data_calc.sum()
caq_data_calc['Region'] = 'Asia-Pacific'
caq_data_calc.reset_index(inplace=True)
rename_to = ['Goods Trade', 'Services Trade','Primary Income','Secondary Income',]
rename_from = ['BoP: Current Account: Goods','BoP: Current Account: Services','BoP: Current Account: Primary Income','BoP: Current Account: Secondary Income',]
caq_data_calc['Type'] = caq_data_calc['Type'].replace(rename_from, rename_to)
caq_data_calc = caq_data_calc.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(rename_to)}))
caq_data_calc.reset_index(drop=True, inplace=True)
caq_data_calc.insert(loc=0, column='Group', value='Current Account')

###################### this is for caq data ######################

df_main = pd.concat([df_by_region_main, df_by_region_main2, caq_data_calc], axis = 0) ## combine
df_main.reset_index(drop=True, inplace=True)

df_temp_col_1, df_all_annual_2, df_main